export type ClubPreset = {
  id: string;
  name: string;
  country: string;
  league: string;
  logoUrl?: string;
  primaryColor: string;
  secondaryColor: string;
  colorBalance: number;
  aliases?: string[];
  shirtImageUrl?: string;
};

export const clubPresets: ClubPreset[] = [
  /* =========================
     NETHERLANDS — EREDIVISIE
     ========================= */

  {
    id: "ajax",
    name: "Ajax",
    country: "Netherlands",
    league: "Eredivisie",
    logoUrl: "/logos/netherlands/eredivisie/ajax.png",
    primaryColor: "#D71920",
    secondaryColor: "#FFFFFF",
    colorBalance: 72,
    aliases: ["AFC Ajax"],
    shirtImageUrl: "/shirts/netherlands/eredivisie/ajax.png",
  },
  {
    id: "az",
    name: "AZ",
    country: "Netherlands",
    league: "Eredivisie",
    logoUrl: "/logos/netherlands/eredivisie/az.png",
    primaryColor: "#D0001B",
    secondaryColor: "#FFFFFF",
    colorBalance: 72,
    aliases: ["AZ Alkmaar"],
  },
  {
    id: "excelsior",
    name: "Excelsior",
    country: "Netherlands",
    league: "Eredivisie",
    logoUrl: "/logos/netherlands/eredivisie/excelsior.png",
    primaryColor: "#000000",
    secondaryColor: "#E30613",
    colorBalance: 64,
  },
  {
    id: "fc-groningen",
    name: "FC Groningen",
    country: "Netherlands",
    league: "Eredivisie",
    logoUrl: "/logos/netherlands/eredivisie/fc-groningen.png",
    primaryColor: "#00853F",
    secondaryColor: "#FFFFFF",
    colorBalance: 72,
  },
  {
    id: "fc-twente",
    name: "FC Twente",
    country: "Netherlands",
    league: "Eredivisie",
    logoUrl: "/logos/netherlands/eredivisie/fc-twente.png",
    primaryColor: "#E30613",
    secondaryColor: "#FFFFFF",
    colorBalance: 70,
    aliases: ["FC Twente Enschede"],
  },
  {
    id: "fc-utrecht",
    name: "FC Utrecht",
    country: "Netherlands",
    league: "Eredivisie",
    logoUrl: "/logos/netherlands/eredivisie/fc-utrecht.png",
    primaryColor: "#E30613",
    secondaryColor: "#FFFFFF",
    colorBalance: 70,
  },
  {
    id: "fc-volendam",
    name: "FC Volendam",
    country: "Netherlands",
    league: "Eredivisie",
    logoUrl: "/logos/netherlands/eredivisie/fc-volendam.png",
    primaryColor: "#F58220",
    secondaryColor: "#000000",
    colorBalance: 70,
  },
  {
    id: "feyenoord",
    name: "Feyenoord",
    country: "Netherlands",
    league: "Eredivisie",
    logoUrl: "/logos/netherlands/eredivisie/feyenoord.png",
    primaryColor: "#D4001F",
    secondaryColor: "#FFFFFF",
    colorBalance: 72,
    aliases: ["Feyenoord Rotterdam"],
  },
  {
    id: "fortuna-sittard",
    name: "Fortuna Sittard",
    country: "Netherlands",
    league: "Eredivisie",
    logoUrl: "/logos/netherlands/eredivisie/fortuna-sittard.png",
    primaryColor: "#FFD200",
    secondaryColor: "#009640",
    colorBalance: 62,
  },
  {
    id: "go-ahead-eagles",
    name: "Go Ahead Eagles",
    country: "Netherlands",
    league: "Eredivisie",
    logoUrl: "/logos/netherlands/eredivisie/go-ahead-eagles.png",
    primaryColor: "#C8102E",
    secondaryColor: "#FFD100",
    colorBalance: 66,
  },
  {
    id: "heracles-almelo",
    name: "Heracles Almelo",
    country: "Netherlands",
    league: "Eredivisie",
    logoUrl: "/logos/netherlands/eredivisie/heracles-almelo.png",
    primaryColor: "#000000",
    secondaryColor: "#FFFFFF",
    colorBalance: 70,
  },
  {
    id: "nac-breda",
    name: "NAC Breda",
    country: "Netherlands",
    league: "Eredivisie",
    logoUrl: "/logos/netherlands/eredivisie/nac-breda.png",
    primaryColor: "#F5D000",
    secondaryColor: "#000000",
    colorBalance: 68,
  },
  {
    id: "nec",
    name: "NEC",
    country: "Netherlands",
    league: "Eredivisie",
    logoUrl: "/logos/netherlands/eredivisie/nec.png",
    primaryColor: "#D71920",
    secondaryColor: "#00853F",
    colorBalance: 62,
    aliases: ["N.E.C.", "N.E.C. Nijmegen", "NEC Nijmegen"],
  },
  {
    id: "pec-zwolle",
    name: "PEC Zwolle",
    country: "Netherlands",
    league: "Eredivisie",
    logoUrl: "/logos/netherlands/eredivisie/pec-zwolle.png",
    primaryColor: "#0057B8",
    secondaryColor: "#FFFFFF",
    colorBalance: 72,
  },
  {
    id: "psv",
    name: "PSV",
    country: "Netherlands",
    league: "Eredivisie",
    logoUrl: "/logos/netherlands/eredivisie/psv.png",
    primaryColor: "#E30613",
    secondaryColor: "#FFFFFF",
    colorBalance: 72,
    aliases: ["PSV Eindhoven"],
  },
  {
    id: "sc-heerenveen",
    name: "sc Heerenveen",
    country: "Netherlands",
    league: "Eredivisie",
    logoUrl: "/logos/netherlands/eredivisie/sc-heerenveen.png",
    primaryColor: "#003DA5",
    secondaryColor: "#FFFFFF",
    colorBalance: 72,
    aliases: ["Heerenveen"],
  },
  {
    id: "sparta-rotterdam",
    name: "Sparta Rotterdam",
    country: "Netherlands",
    league: "Eredivisie",
    logoUrl: "/logos/netherlands/eredivisie/sparta-rotterdam.png",
    primaryColor: "#D71920",
    secondaryColor: "#FFFFFF",
    colorBalance: 72,
  },
  {
    id: "telstar",
    name: "Telstar",
    country: "Netherlands",
    league: "Eredivisie",
    logoUrl: "/logos/netherlands/eredivisie/telstar.png",
    primaryColor: "#FFFFFF",
    secondaryColor: "#003DA5",
    colorBalance: 64,
  },
  

  /* ==================
     NETHERLANDS — KKD
     ================== */

  {
    id: "ado-den-haag",
    name: "ADO Den Haag",
    country: "Netherlands",
    league: "KKD",
    logoUrl: "/logos/netherlands/kkd/ado-den-haag.png",
    primaryColor: "#007A33",
    secondaryColor: "#F7D117",
    colorBalance: 66,
  },
  {
    id: "almere-city",
    name: "Almere City",
    country: "Netherlands",
    league: "KKD",
    logoUrl: "/logos/netherlands/kkd/almere-city.png",
    primaryColor: "#E30613",
    secondaryColor: "#000000",
    colorBalance: 64,
  },
  {
    id: "de-graafschap",
    name: "De Graafschap",
    country: "Netherlands",
    league: "KKD",
    logoUrl: "/logos/netherlands/kkd/de-graafschap.png",
    primaryColor: "#004B9B",
    secondaryColor: "#FFFFFF",
    colorBalance: 72,
  },
  {
    id: "fc-den-bosch",
    name: "FC Den Bosch",
    country: "Netherlands",
    league: "KKD",
    logoUrl: "/logos/netherlands/kkd/fc-den-bosch.png",
    primaryColor: "#0057B8",
    secondaryColor: "#FFFFFF",
    colorBalance: 72,
  },
  {
    id: "fc-dordrecht",
    name: "FC Dordrecht",
    country: "Netherlands",
    league: "KKD",
    logoUrl: "/logos/netherlands/kkd/fc-dordrecht.png",
    primaryColor: "#00853F",
    secondaryColor: "#FFFFFF",
    colorBalance: 72,
  },
  {
    id: "fc-eindhoven",
    name: "FC Eindhoven",
    country: "Netherlands",
    league: "KKD",
    logoUrl: "/logos/netherlands/kkd/fc-eindhoven.png",
    primaryColor: "#0057B8",
    secondaryColor: "#FFFFFF",
    colorBalance: 72,
  },
  {
    id: "fc-emmen",
    name: "FC Emmen",
    country: "Netherlands",
    league: "KKD",
    logoUrl: "/logos/netherlands/kkd/fc-emmen.png",
    primaryColor: "#E30613",
    secondaryColor: "#FFFFFF",
    colorBalance: 72,
  },
  {
    id: "helmond-sport",
    name: "Helmond Sport",
    country: "Netherlands",
    league: "KKD",
    logoUrl: "/logos/netherlands/kkd/helmond-sport.png",
    primaryColor: "#000000",
    secondaryColor: "#FFD200",
    colorBalance: 62,
  },
  {
    id: "jong-ajax",
    name: "Jong Ajax",
    country: "Netherlands",
    league: "KKD",
    logoUrl: "/logos/netherlands/kkd/jong-ajax.png",
    primaryColor: "#D71920",
    secondaryColor: "#FFFFFF",
    colorBalance: 72,
  },
  {
    id: "jong-az",
    name: "Jong AZ",
    country: "Netherlands",
    league: "KKD",
    logoUrl: "/logos/netherlands/kkd/jong-az.png",
    primaryColor: "#D0001B",
    secondaryColor: "#FFFFFF",
    colorBalance: 72,
  },
  {
    id: "jong-psv",
    name: "Jong PSV",
    country: "Netherlands",
    league: "KKD",
    logoUrl: "/logos/netherlands/kkd/jong-psv.png",
    primaryColor: "#E30613",
    secondaryColor: "#FFFFFF",
    colorBalance: 72,
  },
  {
    id: "jong-utrecht",
    name: "Jong Utrecht",
    country: "Netherlands",
    league: "KKD",
    logoUrl: "/logos/netherlands/kkd/jong-utrecht.png",
    primaryColor: "#E30613",
    secondaryColor: "#FFFFFF",
    colorBalance: 70,
  },
  {
    id: "mvv-maastricht",
    name: "MVV Maastricht",
    country: "Netherlands",
    league: "KKD",
    logoUrl: "/logos/netherlands/kkd/mvv-maastricht.png",
    primaryColor: "#C8102E",
    secondaryColor: "#FFFFFF",
    colorBalance: 72,
  },
  {
    id: "rkc-waalwijk",
    name: "RKC Waalwijk",
    country: "Netherlands",
    league: "KKD",
    logoUrl: "/logos/netherlands/kkd/rkc-waalwijk.png",
    primaryColor: "#FFD200",
    secondaryColor: "#0057B8",
    colorBalance: 66,
  },
  {
    id: "roda-jc",
    name: "Roda JC",
    country: "Netherlands",
    league: "KKD",
    logoUrl: "/logos/netherlands/kkd/roda-jc.png",
    primaryColor: "#FFD200",
    secondaryColor: "#000000",
    colorBalance: 68,
    aliases: ["Roda JC Kerkrade"],
  },
  {
    id: "sc-cambuur",
    name: "SC Cambuur",
    country: "Netherlands",
    league: "KKD",
    logoUrl: "/logos/netherlands/kkd/sc-cambuur.png",
    primaryColor: "#FFD200",
    secondaryColor: "#0057B8",
    colorBalance: 66,
    aliases: ["Cambuur"],
  },
  {
    id: "top-oss",
    name: "TOP Oss",
    country: "Netherlands",
    league: "KKD",
    logoUrl: "/logos/netherlands/kkd/top-oss.png",
    primaryColor: "#D71920",
    secondaryColor: "#FFFFFF",
    colorBalance: 72,
  },
  {
    id: "vitesse",
    name: "Vitesse",
    country: "Netherlands",
    league: "KKD",
    logoUrl: "/logos/netherlands/kkd/vitesse.png",
    primaryColor: "#FFD200",
    secondaryColor: "#000000",
    colorBalance: 68,
  },
  {
    id: "vvv-venlo",
    name: "VVV-Venlo",
    country: "Netherlands",
    league: "KKD",
    logoUrl: "/logos/netherlands/kkd/vvv-venlo.png",
    primaryColor: "#FFD200",
    secondaryColor: "#000000",
    colorBalance: 68,
  },
  {
    id: "willem-ii",
    name: "Willem II",
    country: "Netherlands",
    league: "KKD",
    logoUrl: "/logos/netherlands/kkd/willem-ii.png",
    primaryColor: "#D71920",
    secondaryColor: "#0057B8",
    colorBalance: 62,
    aliases: ["Willem II Tilburg"],
  },
/* =========================
   ENGLAND — PREMIER LEAGUE
   ========================= */

{
  id: "arsenal",
  name: "Arsenal",
  country: "England",
  league: "Premier League",
  logoUrl: "/logos/england/premier-league/arsenal.png",
  primaryColor: "#EF0107",
  secondaryColor: "#FFFFFF",
  colorBalance: 74,
  aliases: ["Arsenal FC"],
  shirtImageUrl: "/shirts/england/premier-league/arsenal.png",
},
{
  id: "aston-villa",
  name: "Aston Villa",
  country: "England",
  league: "Premier League",
  logoUrl: "/logos/england/premier-league/aston-villa.png",
  primaryColor: "#670E36",
  secondaryColor: "#95BFE5",
  colorBalance: 68,
  aliases: ["AVFC"],
  shirtImageUrl: "/shirts/england/premier-league/aston-villa.png",
},
{
  id: "bournemouth",
  name: "Bournemouth",
  country: "England",
  league: "Premier League",
  logoUrl: "/logos/england/premier-league/bournemouth.png",
  primaryColor: "#DA291C",
  secondaryColor: "#000000",
  colorBalance: 64,
  aliases: ["AFC Bournemouth"],
  shirtImageUrl: "/shirts/england/premier-league/bournemouth.png",
},
{
  id: "brentford",
  name: "Brentford",
  country: "England",
  league: "Premier League",
  logoUrl: "/logos/england/premier-league/brentford.png",
  primaryColor: "#E30613",
  secondaryColor: "#FFFFFF",
  colorBalance: 70,
  aliases: ["Brentford FC"],
  shirtImageUrl: "/shirts/england/premier-league/brentford.png",
},
{
  id: "brighton",
  name: "Brighton & Hove Albion",
  country: "England",
  league: "Premier League",
  logoUrl: "/logos/england/premier-league/brighton.png",
  primaryColor: "#0057B8",
  secondaryColor: "#FFFFFF",
  colorBalance: 72,
  aliases: ["Brighton"],
  shirtImageUrl: "/shirts/england/premier-league/brighton.png",
},
{
  id: "burnley",
  name: "Burnley",
  country: "England",
  league: "Premier League",
  logoUrl: "/logos/england/premier-league/burnley.png",
  primaryColor: "#6C1D45",
  secondaryColor: "#99D6EA",
  colorBalance: 66,
  aliases: ["Burnley FC"],
  shirtImageUrl: "/shirts/england/premier-league/burnley.png",
},
{
  id: "chelsea",
  name: "Chelsea",
  country: "England",
  league: "Premier League",
  logoUrl: "/logos/england/premier-league/chelsea.png",
  primaryColor: "#034694",
  secondaryColor: "#FFFFFF",
  colorBalance: 76,
  aliases: ["Chelsea FC"],
  shirtImageUrl: "/shirts/england/premier-league/chelsea.png",
},
{
  id: "crystal-palace",
  name: "Crystal Palace",
  country: "England",
  league: "Premier League",
  logoUrl: "/logos/england/premier-league/crystal-palace.png",
  primaryColor: "#1B458F",
  secondaryColor: "#C4122E",
  colorBalance: 60,
  aliases: ["Palace"],
  shirtImageUrl: "/shirts/england/premier-league/crystal-palace.png",
},
{
  id: "everton",
  name: "Everton",
  country: "England",
  league: "Premier League",
  logoUrl: "/logos/england/premier-league/everton.png",
  primaryColor: "#003399",
  secondaryColor: "#FFFFFF",
  colorBalance: 76,
  aliases: ["Everton FC"],
  shirtImageUrl: "/shirts/england/premier-league/everton.png",
},
{
  id: "fulham",
  name: "Fulham",
  country: "England",
  league: "Premier League",
  logoUrl: "/logos/england/premier-league/fulham.png",
  primaryColor: "#FFFFFF",
  secondaryColor: "#000000",
  colorBalance: 68,
  aliases: ["Fulham FC"],
  shirtImageUrl: "/shirts/england/premier-league/fulham.png",
},
{
  id: "leeds",
  name: "Leeds United",
  country: "England",
  league: "Premier League",
  logoUrl: "/logos/england/premier-league/leeds.png",
  primaryColor: "#FFFFFF",
  secondaryColor: "#1D428A",
  colorBalance: 70,
  aliases: ["Leeds"],
  shirtImageUrl: "/shirts/england/premier-league/leeds.png",
},
{
  id: "liverpool",
  name: "Liverpool",
  country: "England",
  league: "Premier League",
  logoUrl: "/logos/england/premier-league/liverpool.png",
  primaryColor: "#C8102E",
  secondaryColor: "#00B2A9",
  colorBalance: 78,
  aliases: ["Liverpool FC"],
  shirtImageUrl: "/shirts/england/premier-league/liverpool.png",
},
{
  id: "man-city",
  name: "Manchester City",
  country: "England",
  league: "Premier League",
  logoUrl: "/logos/england/premier-league/manchester-city.png",
  primaryColor: "#6CABDD",
  secondaryColor: "#1C2C5B",
  colorBalance: 72,
  aliases: ["Man City"],
  shirtImageUrl: "/shirts/england/premier-league/man-city.png",
},
{
  id: "man-united",
  name: "Manchester United",
  country: "England",
  league: "Premier League",
  logoUrl: "/logos/england/premier-league/manchester-united.png",
  primaryColor: "#DA291C",
  secondaryColor: "#FFFFFF",
  colorBalance: 74,
  aliases: ["Man United"],
  shirtImageUrl: "/shirts/england/premier-league/man-united.png",
},
{
  id: "newcastle",
  name: "Newcastle United",
  country: "England",
  league: "Premier League",
  logoUrl: "/logos/england/premier-league/newcastle.png",
  primaryColor: "#000000",
  secondaryColor: "#FFFFFF",
  colorBalance: 62,
  aliases: ["Newcastle"],
  shirtImageUrl: "/shirts/england/premier-league/newcastle.png",
},
{
  id: "nottingham-forest",
  name: "Nottingham Forest",
  country: "England",
  league: "Premier League",
  logoUrl: "/logos/england/premier-league/nottingham-forest.png",
  primaryColor: "#DD0000",
  secondaryColor: "#FFFFFF",
  colorBalance: 74,
  aliases: ["Forest"],
  shirtImageUrl: "/shirts/england/premier-league/nottingham-forest.png",
},
{
  id: "sunderland",
  name: "Sunderland",
  country: "England",
  league: "Premier League",
  logoUrl: "/logos/england/premier-league/sunderland.png",
  primaryColor: "#EB172B",
  secondaryColor: "#FFFFFF",
  colorBalance: 70,
  aliases: ["Sunderland AFC"],
  shirtImageUrl: "/shirts/england/premier-league/sunderland.png",
},
{
  id: "tottenham",
  name: "Tottenham Hotspur",
  country: "England",
  league: "Premier League",
  logoUrl: "/logos/england/premier-league/tottenham.png",
  primaryColor: "#FFFFFF",
  secondaryColor: "#132257",
  colorBalance: 72,
  aliases: ["Spurs"],
  shirtImageUrl: "/shirts/england/premier-league/tottenham.png",
},
{
  id: "west-ham",
  name: "West Ham United",
  country: "England",
  league: "Premier League",
  logoUrl: "/logos/england/premier-league/west-ham.png",
  primaryColor: "#7A263A",
  secondaryColor: "#1BB1E7",
  colorBalance: 66,
  aliases: ["West Ham"],
  shirtImageUrl: "/shirts/england/premier-league/west-ham.png",
},
{
  id: "wolves",
  name: "Wolverhampton Wanderers",
  country: "England",
  league: "Premier League",
  logoUrl: "/logos/england/premier-league/wolves.png",
  primaryColor: "#FDB913",
  secondaryColor: "#231F20",
  colorBalance: 74,
  aliases: ["Wolves"],
  shirtImageUrl: "/shirts/england/premier-league/wolves.png",
},

/* =========================
   ENGLAND — CHAMPIONSHIP
   ========================= */

{
  id: "birmingham-city",
  name: "Birmingham City",
  country: "England",
  league: "Championship",
  logoUrl: "/logos/england/championship/birmingham-city.png",
  primaryColor: "#0046AE",
  secondaryColor: "#FFFFFF",
  colorBalance: 74,
  aliases: ["Birmingham"],
  shirtImageUrl: "/shirts/england/championship/birmingham-city.png",
},
{
  id: "blackburn",
  name: "Blackburn Rovers",
  country: "England",
  league: "Championship",
  logoUrl: "/logos/england/championship/blackburn.png",
  primaryColor: "#1F4FA3",
  secondaryColor: "#FFFFFF",
  colorBalance: 64,
  aliases: ["Blackburn"],
  shirtImageUrl: "/shirts/england/championship/blackburn.png",
},
{
  id: "bristol-city",
  name: "Bristol City",
  country: "England",
  league: "Championship",
  logoUrl: "/logos/england/championship/bristol-city.png",
  primaryColor: "#E31B23",
  secondaryColor: "#FFFFFF",
  colorBalance: 72,
  aliases: ["Bristol City FC"],
  shirtImageUrl: "/shirts/england/championship/bristol-city.png",
},
{
  id: "charlton",
  name: "Charlton Athletic",
  country: "England",
  league: "Championship",
  logoUrl: "/logos/england/championship/charlton.png",
  primaryColor: "#D71920",
  secondaryColor: "#FFFFFF",
  colorBalance: 72,
  aliases: ["Charlton"],
  shirtImageUrl: "/shirts/england/championship/charlton.png",
},
{
  id: "coventry",
  name: "Coventry City",
  country: "England",
  league: "Championship",
  logoUrl: "/logos/england/championship/coventry.png",
  primaryColor: "#6CABDD",
  secondaryColor: "#FFFFFF",
  colorBalance: 74,
  aliases: ["Coventry"],
  shirtImageUrl: "/shirts/england/championship/coventry.png",
},
{
  id: "derby-county",
  name: "Derby County",
  country: "England",
  league: "Championship",
  logoUrl: "/logos/england/championship/derby-county.png",
  primaryColor: "#FFFFFF",
  secondaryColor: "#000000",
  colorBalance: 66,
  aliases: ["Derby"],
  shirtImageUrl: "/shirts/england/championship/derby-county.png",
},
{
  id: "hull-city",
  name: "Hull City",
  country: "England",
  league: "Championship",
  logoUrl: "/logos/england/championship/hull-city.png",
  primaryColor: "#F28C28",
  secondaryColor: "#000000",
  colorBalance: 68,
  aliases: ["Hull"],
  shirtImageUrl: "/shirts/england/championship/hull-city.png",
},
{
  id: "ipswich",
  name: "Ipswich Town",
  country: "England",
  league: "Championship",
  logoUrl: "/logos/england/championship/ipswich.png",
  primaryColor: "#0057B8",
  secondaryColor: "#FFFFFF",
  colorBalance: 72,
  aliases: ["Ipswich"],
  shirtImageUrl: "/shirts/england/championship/ipswich.png",
},
{
  id: "leicester",
  name: "Leicester City",
  country: "England",
  league: "Championship",
  logoUrl: "/logos/england/championship/leicester.png",
  primaryColor: "#003090",
  secondaryColor: "#FFFFFF",
  colorBalance: 76,
  aliases: ["Leicester"],
  shirtImageUrl: "/shirts/england/championship/leicester.png",
},
{
  id: "middlesbrough",
  name: "Middlesbrough",
  country: "England",
  league: "Championship",
  logoUrl: "/logos/england/championship/middlesbrough.png",
  primaryColor: "#D71920",
  secondaryColor: "#FFFFFF",
  colorBalance: 74,
  aliases: ["Boro"],
  shirtImageUrl: "/shirts/england/championship/middlesbrough.png",
},
{
  id: "millwall",
  name: "Millwall",
  country: "England",
  league: "Championship",
  logoUrl: "/logos/england/championship/millwall.png",
  primaryColor: "#002E5D",
  secondaryColor: "#FFFFFF",
  colorBalance: 72,
  aliases: ["Millwall FC"],
  shirtImageUrl: "/shirts/england/championship/millwall.png",
},
{
  id: "norwich",
  name: "Norwich City",
  country: "England",
  league: "Championship",
  logoUrl: "/logos/england/championship/norwich.png",
  primaryColor: "#FFF200",
  secondaryColor: "#00A650",
  colorBalance: 66,
  aliases: ["Norwich"],
  shirtImageUrl: "/shirts/england/championship/norwich.png",
},
{
  id: "oxford-united",
  name: "Oxford United",
  country: "England",
  league: "Championship",
  logoUrl: "/logos/england/championship/oxford-united.png",
  primaryColor: "#FFD200",
  secondaryColor: "#002147",
  colorBalance: 70,
  aliases: ["Oxford"],
  shirtImageUrl: "/shirts/england/championship/oxford-united.png",
},
{
  id: "portsmouth",
  name: "Portsmouth",
  country: "England",
  league: "Championship",
  logoUrl: "/logos/england/championship/portsmouth.png",
  primaryColor: "#003087",
  secondaryColor: "#FFFFFF",
  colorBalance: 74,
  aliases: ["Pompey"],
  shirtImageUrl: "/shirts/england/championship/portsmouth.png",
},
{
  id: "preston",
  name: "Preston North End",
  country: "England",
  league: "Championship",
  logoUrl: "/logos/england/championship/preston.png",
  primaryColor: "#FFFFFF",
  secondaryColor: "#003366",
  colorBalance: 66,
  aliases: ["Preston"],
  shirtImageUrl: "/shirts/england/championship/preston.png",
},
{
  id: "qpr",
  name: "Queens Park Rangers",
  country: "England",
  league: "Championship",
  logoUrl: "/logos/england/championship/qpr.png",
  primaryColor: "#1B458F",
  secondaryColor: "#FFFFFF",
  colorBalance: 64,
  aliases: ["QPR"],
  shirtImageUrl: "/shirts/england/championship/qpr.png",
},
{
  id: "sheffield-united",
  name: "Sheffield United",
  country: "England",
  league: "Championship",
  logoUrl: "/logos/england/championship/sheffield-united.png",
  primaryColor: "#EE2737",
  secondaryColor: "#000000",
  colorBalance: 68,
  aliases: ["Sheff United"],
  shirtImageUrl: "/shirts/england/championship/sheffield-united.png",
},
{
  id: "sheffield-wednesday",
  name: "Sheffield Wednesday",
  country: "England",
  league: "Championship",
  logoUrl: "/logos/england/championship/sheffield-wednesday.png",
  primaryColor: "#0057B8",
  secondaryColor: "#FFFFFF",
  colorBalance: 68,
  aliases: ["Sheff Wednesday"],
  shirtImageUrl: "/shirts/england/championship/sheffield-wednesday.png",
},
{
  id: "southampton",
  name: "Southampton",
  country: "England",
  league: "Championship",
  logoUrl: "/logos/england/championship/southampton.png",
  primaryColor: "#D71920",
  secondaryColor: "#FFFFFF",
  colorBalance: 70,
  aliases: ["Saints"],
  shirtImageUrl: "/shirts/england/championship/southampton.png",
},
{
  id: "stoke-city",
  name: "Stoke City",
  country: "England",
  league: "Championship",
  logoUrl: "/logos/england/championship/stoke-city.png",
  primaryColor: "#E03A3E",
  secondaryColor: "#FFFFFF",
  colorBalance: 70,
  aliases: ["Stoke"],
  shirtImageUrl: "/shirts/england/championship/stoke-city.png",
},
{
  id: "swansea",
  name: "Swansea City",
  country: "England",
  league: "Championship",
  logoUrl: "/logos/england/championship/swansea.png",
  primaryColor: "#FFFFFF",
  secondaryColor: "#000000",
  colorBalance: 68,
  aliases: ["Swansea"],
  shirtImageUrl: "/shirts/england/championship/swansea.png",
},
{
  id: "watford",
  name: "Watford",
  country: "England",
  league: "Championship",
  logoUrl: "/logos/england/championship/watford.png",
  primaryColor: "#FBEE23",
  secondaryColor: "#ED2127",
  colorBalance: 66,
  aliases: ["Watford FC"],
  shirtImageUrl: "/shirts/england/championship/watford.png",
},
{
  id: "west-brom",
  name: "West Bromwich Albion",
  country: "England",
  league: "Championship",
  logoUrl: "/logos/england/championship/west-brom.png",
  primaryColor: "#122F67",
  secondaryColor: "#FFFFFF",
  colorBalance: 66,
  aliases: ["West Brom"],
  shirtImageUrl: "/shirts/england/championship/west-brom.png",
},
{
  id: "wrexham",
  name: "Wrexham",
  country: "England",
  league: "Championship",
  logoUrl: "/logos/england/championship/wrexham.png",
  primaryColor: "#E31B23",
  secondaryColor: "#FFFFFF",
  colorBalance: 72,
  aliases: ["Wrexham AFC"],
  shirtImageUrl: "/shirts/england/championship/wrexham.png",
},
/* =========================
   ITALY — SERIE A
   ========================= */

{
  id: "atalanta",
  name: "Atalanta",
  country: "Italy",
  league: "Serie A",
  logoUrl: "/logos/italy/serie-a/atalanta.png",
  primaryColor: "#00529F",
  secondaryColor: "#000000",
  colorBalance: 58,
  aliases: ["Atalanta BC"],
  shirtImageUrl: "/shirts/italy/serie-a/atalanta.png",
},
{
  id: "bologna",
  name: "Bologna",
  country: "Italy",
  league: "Serie A",
  logoUrl: "/logos/italy/serie-a/bologna.png",
  primaryColor: "#9E1B32",
  secondaryColor: "#1D4E89",
  colorBalance: 58,
  aliases: ["Bologna FC", "Bologna FC 1909"],
  shirtImageUrl: "/shirts/italy/serie-a/bologna.png",
},
{
  id: "cagliari",
  name: "Cagliari",
  country: "Italy",
  league: "Serie A",
  logoUrl: "/logos/italy/serie-a/cagliari.png",
  primaryColor: "#C8102E",
  secondaryColor: "#003B7A",
  colorBalance: 56,
  aliases: ["Cagliari Calcio"],
  shirtImageUrl: "/shirts/italy/serie-a/cagliari.png",
},
{
  id: "como",
  name: "Como",
  country: "Italy",
  league: "Serie A",
  logoUrl: "/logos/italy/serie-a/como.png",
  primaryColor: "#0054A6",
  secondaryColor: "#FFFFFF",
  colorBalance: 74,
  aliases: ["Como 1907"],
  shirtImageUrl: "/shirts/italy/serie-a/como.png",
},
{
  id: "cremonese",
  name: "Cremonese",
  country: "Italy",
  league: "Serie A",
  logoUrl: "/logos/italy/serie-a/cremonese.png",
  primaryColor: "#A6192E",
  secondaryColor: "#8E8C89",
  colorBalance: 66,
  aliases: ["US Cremonese"],
  shirtImageUrl: "/shirts/italy/serie-a/cremonese.png",
},
{
  id: "fiorentina",
  name: "Fiorentina",
  country: "Italy",
  league: "Serie A",
  logoUrl: "/logos/italy/serie-a/fiorentina.png",
  primaryColor: "#5B2C83",
  secondaryColor: "#FFFFFF",
  colorBalance: 76,
  aliases: ["ACF Fiorentina"],
  shirtImageUrl: "/shirts/italy/serie-a/fiorentina.png",
},
{
  id: "genoa",
  name: "Genoa",
  country: "Italy",
  league: "Serie A",
  logoUrl: "/logos/italy/serie-a/genoa.png",
  primaryColor: "#A6192E",
  secondaryColor: "#003087",
  colorBalance: 54,
  aliases: ["Genoa CFC"],
  shirtImageUrl: "/shirts/italy/serie-a/genoa.png",
},
{
  id: "hellas-verona",
  name: "Hellas Verona",
  country: "Italy",
  league: "Serie A",
  logoUrl: "/logos/italy/serie-a/hellas-verona.png",
  primaryColor: "#FFD100",
  secondaryColor: "#1E4FA1",
  colorBalance: 54,
  aliases: ["Verona", "Hellas"],
  shirtImageUrl: "/shirts/italy/serie-a/hellas-verona.png",
},
{
  id: "inter",
  name: "Inter",
  country: "Italy",
  league: "Serie A",
  logoUrl: "/logos/italy/serie-a/inter.png",
  primaryColor: "#00529F",
  secondaryColor: "#000000",
  colorBalance: 56,
  aliases: ["Internazionale", "Inter Milan"],
  shirtImageUrl: "/shirts/italy/serie-a/inter.png",
},
{
  id: "juventus",
  name: "Juventus",
  country: "Italy",
  league: "Serie A",
  logoUrl: "/logos/italy/serie-a/juventus.png",
  primaryColor: "#FFFFFF",
  secondaryColor: "#000000",
  colorBalance: 60,
  aliases: ["Juve"],
  shirtImageUrl: "/shirts/italy/serie-a/juventus.png",
},
{
  id: "lazio",
  name: "Lazio",
  country: "Italy",
  league: "Serie A",
  logoUrl: "/logos/italy/serie-a/lazio.png",
  primaryColor: "#9BCBEB",
  secondaryColor: "#FFFFFF",
  colorBalance: 72,
  aliases: ["SS Lazio"],
  shirtImageUrl: "/shirts/italy/serie-a/lazio.png",
},
{
  id: "lecce",
  name: "Lecce",
  country: "Italy",
  league: "Serie A",
  logoUrl: "/logos/italy/serie-a/lecce.png",
  primaryColor: "#F5C400",
  secondaryColor: "#C8102E",
  colorBalance: 58,
  aliases: ["US Lecce"],
  shirtImageUrl: "/shirts/italy/serie-a/lecce.png",
},
{
  id: "milan",
  name: "Milan",
  country: "Italy",
  league: "Serie A",
  logoUrl: "/logos/italy/serie-a/milan.png",
  primaryColor: "#D71920",
  secondaryColor: "#000000",
  colorBalance: 56,
  aliases: ["AC Milan"],
  shirtImageUrl: "/shirts/italy/serie-a/milan.png",
},
{
  id: "napoli",
  name: "Napoli",
  country: "Italy",
  league: "Serie A",
  logoUrl: "/logos/italy/serie-a/napoli.png",
  primaryColor: "#0085CA",
  secondaryColor: "#FFFFFF",
  colorBalance: 78,
  aliases: ["SSC Napoli"],
  shirtImageUrl: "/shirts/italy/serie-a/napoli.png",
},
{
  id: "parma",
  name: "Parma",
  country: "Italy",
  league: "Serie A",
  logoUrl: "/logos/italy/serie-a/parma.png",
  primaryColor: "#FFD100",
  secondaryColor: "#1F2A44",
  colorBalance: 52,
  aliases: ["Parma Calcio"],
  shirtImageUrl: "/shirts/italy/serie-a/parma.png",
},
{
  id: "pisa",
  name: "Pisa",
  country: "Italy",
  league: "Serie A",
  logoUrl: "/logos/italy/serie-a/pisa.png",
  primaryColor: "#0F172A",
  secondaryColor: "#1D4E89",
  colorBalance: 68,
  aliases: ["Pisa SC"],
  shirtImageUrl: "/shirts/italy/serie-a/pisa.png",
},
{
  id: "roma",
  name: "Roma",
  country: "Italy",
  league: "Serie A",
  logoUrl: "/logos/italy/serie-a/roma.png",
  primaryColor: "#8E1F2F",
  secondaryColor: "#F7B500",
  colorBalance: 62,
  aliases: ["AS Roma"],
  shirtImageUrl: "/shirts/italy/serie-a/roma.png",
},
{
  id: "sassuolo",
  name: "Sassuolo",
  country: "Italy",
  league: "Serie A",
  logoUrl: "/logos/italy/serie-a/sassuolo.png",
  primaryColor: "#00A651",
  secondaryColor: "#000000",
  colorBalance: 64,
  aliases: ["US Sassuolo", "Sassuolo Calcio"],
  shirtImageUrl: "/shirts/italy/serie-a/sassuolo.png",
},
{
  id: "torino",
  name: "Torino",
  country: "Italy",
  league: "Serie A",
  logoUrl: "/logos/italy/serie-a/torino.png",
  primaryColor: "#7B1E3A",
  secondaryColor: "#FFFFFF",
  colorBalance: 76,
  aliases: ["Torino FC"],
  shirtImageUrl: "/shirts/italy/serie-a/torino.png",
},
{
  id: "udinese",
  name: "Udinese",
  country: "Italy",
  league: "Serie A",
  logoUrl: "/logos/italy/serie-a/udinese.png",
  primaryColor: "#000000",
  secondaryColor: "#FFFFFF",
  colorBalance: 62,
  aliases: ["Udinese Calcio"],
  shirtImageUrl: "/shirts/italy/serie-a/udinese.png",
},

    /* =========================
     BELGIUM — JUPILER PRO LEAGUE
     ========================= */

  {
    id: "anderlecht",
    name: "Anderlecht",
    country: "Belgium",
    league: "Jupiler Pro League",
    logoUrl: "/logos/belgium/jupiler-pro-league/anderlecht.png",
    primaryColor: "#512D6D",
    secondaryColor: "#FFFFFF",
    colorBalance: 72,
    aliases: ["RSC Anderlecht"],
    shirtImageUrl: "/shirts/belgium/jupiler-pro-league/anderlecht.png",
  },
  {
    id: "antwerp",
    name: "Antwerp",
    country: "Belgium",
    league: "Jupiler Pro League",
    logoUrl: "/logos/belgium/jupiler-pro-league/royal-antwerp.png",
    primaryColor: "#D71920",
    secondaryColor: "#FFFFFF",
    colorBalance: 72,
    aliases: ["Royal Antwerp", "Royal Antwerp FC"],
    shirtImageUrl: "/shirts/belgium/jupiler-pro-league/antwerp.png",
  },
  {
    id: "club-brugge",
    name: "Club Brugge",
    country: "Belgium",
    league: "Jupiler Pro League",
    logoUrl: "/logos/belgium/jupiler-pro-league/club-brugge.png",
    primaryColor: "#000000",
    secondaryColor: "#1E5AA8",
    colorBalance: 62,
    aliases: ["Club Brugge KV"],
    shirtImageUrl: "/shirts/belgium/jupiler-pro-league/club-brugge.png",
  },
  {
    id: "cercle-brugge",
    name: "Cercle Brugge",
    country: "Belgium",
    league: "Jupiler Pro League",
    logoUrl: "/logos/belgium/jupiler-pro-league/cercle-brugge.png",
    primaryColor: "#00853F",
    secondaryColor: "#000000",
    colorBalance: 68,
    aliases: ["Cercle Brugge KSV"],
    shirtImageUrl: "/shirts/belgium/jupiler-pro-league/cercle-brugge.png",
  },
  {
    id: "charleroi",
    name: "Charleroi",
    country: "Belgium",
    league: "Jupiler Pro League",
    logoUrl: "/logos/belgium/jupiler-pro-league/charleroi.png",
    primaryColor: "#000000",
    secondaryColor: "#FFFFFF",
    colorBalance: 74,
    aliases: ["Sporting Charleroi", "RC Sporting Charleroi"],
    shirtImageUrl: "/shirts/belgium/jupiler-pro-league/charleroi.png",
  },
  {
    id: "dender",
    name: "Dender",
    country: "Belgium",
    league: "Jupiler Pro League",
    logoUrl: "/logos/belgium/jupiler-pro-league/dender.png",
    primaryColor: "#274185",
    secondaryColor: "#FFFFFF",
    colorBalance: 70,
    aliases: ["FCV Dender"],
    shirtImageUrl: "/shirts/belgium/jupiler-pro-league/kortrijk.png",
  },
  {
    id: "genk",
    name: "Genk",
    country: "Belgium",
    league: "Jupiler Pro League",
    logoUrl: "/logos/belgium/jupiler-pro-league/racing-genk.png",
    primaryColor: "#0057B8",
    secondaryColor: "#FFFFFF",
    colorBalance: 74,
    aliases: ["KRC Genk"],
    shirtImageUrl: "/shirts/belgium/jupiler-pro-league/genk.png",
  },
  {
    id: "gent",
    name: "Gent",
    country: "Belgium",
    league: "Jupiler Pro League",
    logoUrl: "/logos/belgium/jupiler-pro-league/kaa-gent.png",
    primaryColor: "#0057B8",
    secondaryColor: "#FFFFFF",
    colorBalance: 72,
    aliases: ["KAA Gent"],
    shirtImageUrl: "/shirts/belgium/jupiler-pro-league/gent.png",
  },
  {
    id: "leuven",
    name: "OH Leuven",
    country: "Belgium",
    league: "Jupiler Pro League",
    logoUrl: "/logos/belgium/jupiler-pro-league/ohl.png",
    primaryColor: "#000000",
    secondaryColor: "#D71920",
    colorBalance: 62,
    aliases: ["Oud-Heverlee Leuven", "OHL"],
    shirtImageUrl: "/shirts/belgium/jupiler-pro-league/leuven.png",
  },
  {
    id: "mechelen",
    name: "KV Mechelen",
    country: "Belgium",
    league: "Jupiler Pro League",
    logoUrl: "/logos/belgium/jupiler-pro-league/kv-mechelen.png",
    primaryColor: "#FFD200",
    secondaryColor: "#D71920",
    colorBalance: 58,
    aliases: ["Mechelen"],
    shirtImageUrl: "/shirts/belgium/jupiler-pro-league/mechelen.png",
  },
  {
    id: "raal",
    name: "Raal La Louvière",
    country: "Belgium",
    league: "Jupiler Pro League",
    logoUrl: "/logos/belgium/jupiler-pro-league/raal-la-louviere.png",
    primaryColor: "#2F7946",
    secondaryColor: "#ffffff",
    colorBalance: 72,
    aliases: ["Raal"],
    shirtImageUrl: "/shirts/belgium/jupiler-pro-league/raal.png",
  },
  {
    id: "standard-liege",
    name: "Standard Liège",
    country: "Belgium",
    league: "Jupiler Pro League",
    logoUrl: "/logos/belgium/jupiler-pro-league/standard.png",
    primaryColor: "#D71920",
    secondaryColor: "#FFFFFF",
    colorBalance: 72,
    aliases: ["Standard", "Standard de Liège"],
    shirtImageUrl: "/shirts/belgium/jupiler-pro-league/standard-liege.png",
  },
  {
    id: "st-truiden",
    name: "STVV",
    country: "Belgium",
    league: "Jupiler Pro League",
    logoUrl: "/logos/belgium/jupiler-pro-league/stvv.png",
    primaryColor: "#FFD200",
    secondaryColor: "#0057B8",
    colorBalance: 62,
    aliases: ["Sint-Truiden", "Sint-Truidense VV"],
    shirtImageUrl: "/shirts/belgium/jupiler-pro-league/st-truiden.png",
  },
  {
    id: "union-sg",
    name: "Union Saint-Gilloise",
    country: "Belgium",
    league: "Jupiler Pro League",
    logoUrl: "/logos/belgium/jupiler-pro-league/union-saint-gilloise.png",
    primaryColor: "#FFD200",
    secondaryColor: "#1E3A8A",
    colorBalance: 60,
    aliases: ["Union SG", "Royale Union Saint-Gilloise"],
    shirtImageUrl: "/shirts/belgium/jupiler-pro-league/union-sg.png",
  },
  {
    id: "westerlo",
    name: "Westerlo",
    country: "Belgium",
    league: "Jupiler Pro League",
    logoUrl: "/logos/belgium/jupiler-pro-league/westerlo.png",
    primaryColor: "#FFD200",
    secondaryColor: "#0057B8",
    colorBalance: 60,
    aliases: ["KVC Westerlo"],
    shirtImageUrl: "/shirts/belgium/jupiler-pro-league/westerlo.png",
  },
  {
    id: "zulte-waregem",
    name: "Zulte Waregem",
    country: "Belgium",
    league: "Jupiler Pro League",
    logoUrl: "/logos/belgium/jupiler-pro-league/zulte-waregem.png",
    primaryColor: "#E21350",
    secondaryColor: "#FFD204",
    colorBalance: 80,
    aliases: ["Zulte", "Essevee"],
    shirtImageUrl: "/shirts/belgium/jupiler-pro-league/westerlo.png",
  },

  /* ======================
     PLACEHOLDERS — OTHER
     ====================== */

  {
    id: "custom-club",
    name: "Custom Club",
    country: "Other",
    league: "Other",
    logoUrl: "",
    primaryColor: "#111111",
    secondaryColor: "#FFFFFF",
    colorBalance: 70,
    aliases: ["Other club", "Andere club"],
  },
];

/* ---------------- HELPERS ---------------- */

function norm(v: string) {
  return v.trim().toLowerCase();
}

export function getClubPresetByName(name: string) {
  const input = norm(name);

  return clubPresets.find((club) => {
    if (norm(club.name) === input) return true;
    if (club.aliases?.some((alias) => norm(alias) === input)) return true;
    return false;
  });
}

export function getClubPresetsByCountry(country: string) {
  return clubPresets.filter((club) => norm(club.country) === norm(country));
}

export function getClubPresetsByCountryAndLeague(country: string, league: string) {
  return clubPresets.filter(
    (club) =>
      norm(club.country) === norm(country) &&
      norm(club.league) === norm(league)
  );
}

export const clubPresetGroups = {
  netherlands: {
    label: "Netherlands",
    leagues: {
      eredivisie: clubPresets.filter(
        (club) => club.country === "Netherlands" && club.league === "Eredivisie"
      ),
      kkd: clubPresets.filter(
        (club) => club.country === "Netherlands" && club.league === "KKD"
      ),
    },
  },
};