export type ClubPreset = {
  id: string;
  name: string;
  country: string;
  league: string;
  logoUrl?: string;
  primaryColor: string;
  secondaryColor: string;
  colorBalance: number;
  aliases?: string[];
  shirtImageUrl?: string;
};

export const clubPresets: ClubPreset[] = [
  /* =========================
     NETHERLANDS — EREDIVISIE
     ========================= */

  {
    id: "ajax",
    name: "Ajax",
    country: "Netherlands",
    league: "Eredivisie",
    logoUrl: "/logos/netherlands/eredivisie/ajax.png",
    primaryColor: "#D71920",
    secondaryColor: "#FFFFFF",
    colorBalance: 72,
    aliases: ["AFC Ajax"],
    shirtImageUrl: "/shirts/netherlands/eredivisie/ajax.png",
  },
  {
    id: "az",
    name: "AZ",
    country: "Netherlands",
    league: "Eredivisie",
    logoUrl: "/logos/netherlands/eredivisie/az.png",
    primaryColor: "#D0001B",
    secondaryColor: "#FFFFFF",
    colorBalance: 72,
    aliases: ["AZ Alkmaar"],
  },
  {
    id: "excelsior",
    name: "Excelsior",
    country: "Netherlands",
    league: "Eredivisie",
    logoUrl: "/logos/netherlands/eredivisie/excelsior.png",
    primaryColor: "#000000",
    secondaryColor: "#E30613",
    colorBalance: 64,
  },
  {
    id: "fc-groningen",
    name: "FC Groningen",
    country: "Netherlands",
    league: "Eredivisie",
    logoUrl: "/logos/netherlands/eredivisie/fc-groningen.png",
    primaryColor: "#00853F",
    secondaryColor: "#FFFFFF",
    colorBalance: 72,
  },
  {
    id: "fc-twente",
    name: "FC Twente",
    country: "Netherlands",
    league: "Eredivisie",
    logoUrl: "/logos/netherlands/eredivisie/fc-twente.png",
    primaryColor: "#E30613",
    secondaryColor: "#FFFFFF",
    colorBalance: 70,
    aliases: ["FC Twente Enschede"],
  },
  {
    id: "fc-utrecht",
    name: "FC Utrecht",
    country: "Netherlands",
    league: "Eredivisie",
    logoUrl: "/logos/netherlands/eredivisie/fc-utrecht.png",
    primaryColor: "#E30613",
    secondaryColor: "#FFFFFF",
    colorBalance: 70,
  },
  {
    id: "fc-volendam",
    name: "FC Volendam",
    country: "Netherlands",
    league: "Eredivisie",
    logoUrl: "/logos/netherlands/eredivisie/fc-volendam.png",
    primaryColor: "#F58220",
    secondaryColor: "#000000",
    colorBalance: 70,
  },
  {
    id: "feyenoord",
    name: "Feyenoord",
    country: "Netherlands",
    league: "Eredivisie",
    logoUrl: "/logos/netherlands/eredivisie/feyenoord.png",
    primaryColor: "#D4001F",
    secondaryColor: "#FFFFFF",
    colorBalance: 72,
    aliases: ["Feyenoord Rotterdam"],
  },
  {
    id: "fortuna-sittard",
    name: "Fortuna Sittard",
    country: "Netherlands",
    league: "Eredivisie",
    logoUrl: "/logos/netherlands/eredivisie/fortuna-sittard.png",
    primaryColor: "#FFD200",
    secondaryColor: "#009640",
    colorBalance: 62,
  },
  {
    id: "go-ahead-eagles",
    name: "Go Ahead Eagles",
    country: "Netherlands",
    league: "Eredivisie",
    logoUrl: "/logos/netherlands/eredivisie/go-ahead-eagles.png",
    primaryColor: "#C8102E",
    secondaryColor: "#FFD100",
    colorBalance: 66,
  },
  {
    id: "heracles-almelo",
    name: "Heracles Almelo",
    country: "Netherlands",
    league: "Eredivisie",
    logoUrl: "/logos/netherlands/eredivisie/heracles-almelo.png",
    primaryColor: "#000000",
    secondaryColor: "#FFFFFF",
    colorBalance: 70,
  },
  {
    id: "nac-breda",
    name: "NAC Breda",
    country: "Netherlands",
    league: "Eredivisie",
    logoUrl: "/logos/netherlands/eredivisie/nac-breda.png",
    primaryColor: "#F5D000",
    secondaryColor: "#000000",
    colorBalance: 68,
  },
  {
    id: "nec",
    name: "NEC",
    country: "Netherlands",
    league: "Eredivisie",
    logoUrl: "/logos/netherlands/eredivisie/nec.png",
    primaryColor: "#D71920",
    secondaryColor: "#00853F",
    colorBalance: 62,
    aliases: ["N.E.C.", "N.E.C. Nijmegen", "NEC Nijmegen"],
  },
  {
    id: "pec-zwolle",
    name: "PEC Zwolle",
    country: "Netherlands",
    league: "Eredivisie",
    logoUrl: "/logos/netherlands/eredivisie/pec-zwolle.png",
    primaryColor: "#0057B8",
    secondaryColor: "#FFFFFF",
    colorBalance: 72,
  },
  {
    id: "psv",
    name: "PSV",
    country: "Netherlands",
    league: "Eredivisie",
    logoUrl: "/logos/netherlands/eredivisie/psv.png",
    primaryColor: "#E30613",
    secondaryColor: "#FFFFFF",
    colorBalance: 72,
    aliases: ["PSV Eindhoven"],
  },
  {
    id: "sc-heerenveen",
    name: "sc Heerenveen",
    country: "Netherlands",
    league: "Eredivisie",
    logoUrl: "/logos/netherlands/eredivisie/sc-heerenveen.png",
    primaryColor: "#003DA5",
    secondaryColor: "#FFFFFF",
    colorBalance: 72,
    aliases: ["Heerenveen"],
  },
  {
    id: "sparta-rotterdam",
    name: "Sparta Rotterdam",
    country: "Netherlands",
    league: "Eredivisie",
    logoUrl: "/logos/netherlands/eredivisie/sparta-rotterdam.png",
    primaryColor: "#D71920",
    secondaryColor: "#FFFFFF",
    colorBalance: 72,
  },
  {
    id: "telstar",
    name: "Telstar",
    country: "Netherlands",
    league: "Eredivisie",
    logoUrl: "/logos/netherlands/eredivisie/telstar.png",
    primaryColor: "#FFFFFF",
    secondaryColor: "#003DA5",
    colorBalance: 64,
  },
  

  /* ==================
     NETHERLANDS — KKD
     ================== */

  {
    id: "ado-den-haag",
    name: "ADO Den Haag",
    country: "Netherlands",
    league: "KKD",
    logoUrl: "/logos/netherlands/kkd/ado-den-haag.png",
    primaryColor: "#007A33",
    secondaryColor: "#F7D117",
    colorBalance: 66,
  },
  {
    id: "almere-city",
    name: "Almere City",
    country: "Netherlands",
    league: "KKD",
    logoUrl: "/logos/netherlands/kkd/almere-city.png",
    primaryColor: "#E30613",
    secondaryColor: "#000000",
    colorBalance: 64,
  },
  {
    id: "de-graafschap",
    name: "De Graafschap",
    country: "Netherlands",
    league: "KKD",
    logoUrl: "/logos/netherlands/kkd/de-graafschap.png",
    primaryColor: "#004B9B",
    secondaryColor: "#FFFFFF",
    colorBalance: 72,
  },
  {
    id: "fc-den-bosch",
    name: "FC Den Bosch",
    country: "Netherlands",
    league: "KKD",
    logoUrl: "/logos/netherlands/kkd/fc-den-bosch.png",
    primaryColor: "#0057B8",
    secondaryColor: "#FFFFFF",
    colorBalance: 72,
  },
  {
    id: "fc-dordrecht",
    name: "FC Dordrecht",
    country: "Netherlands",
    league: "KKD",
    logoUrl: "/logos/netherlands/kkd/fc-dordrecht.png",
    primaryColor: "#00853F",
    secondaryColor: "#FFFFFF",
    colorBalance: 72,
  },
  {
    id: "fc-eindhoven",
    name: "FC Eindhoven",
    country: "Netherlands",
    league: "KKD",
    logoUrl: "/logos/netherlands/kkd/fc-eindhoven.png",
    primaryColor: "#0057B8",
    secondaryColor: "#FFFFFF",
    colorBalance: 72,
  },
  {
    id: "fc-emmen",
    name: "FC Emmen",
    country: "Netherlands",
    league: "KKD",
    logoUrl: "/logos/netherlands/kkd/fc-emmen.png",
    primaryColor: "#E30613",
    secondaryColor: "#FFFFFF",
    colorBalance: 72,
  },
  {
    id: "helmond-sport",
    name: "Helmond Sport",
    country: "Netherlands",
    league: "KKD",
    logoUrl: "/logos/netherlands/kkd/helmond-sport.png",
    primaryColor: "#000000",
    secondaryColor: "#FFD200",
    colorBalance: 62,
  },
  {
    id: "jong-ajax",
    name: "Jong Ajax",
    country: "Netherlands",
    league: "KKD",
    logoUrl: "/logos/netherlands/kkd/jong-ajax.png",
    primaryColor: "#D71920",
    secondaryColor: "#FFFFFF",
    colorBalance: 72,
  },
  {
    id: "jong-az",
    name: "Jong AZ",
    country: "Netherlands",
    league: "KKD",
    logoUrl: "/logos/netherlands/kkd/jong-az.png",
    primaryColor: "#D0001B",
    secondaryColor: "#FFFFFF",
    colorBalance: 72,
  },
  {
    id: "jong-psv",
    name: "Jong PSV",
    country: "Netherlands",
    league: "KKD",
    logoUrl: "/logos/netherlands/kkd/jong-psv.png",
    primaryColor: "#E30613",
    secondaryColor: "#FFFFFF",
    colorBalance: 72,
  },
  {
    id: "jong-utrecht",
    name: "Jong Utrecht",
    country: "Netherlands",
    league: "KKD",
    logoUrl: "/logos/netherlands/kkd/jong-utrecht.png",
    primaryColor: "#E30613",
    secondaryColor: "#FFFFFF",
    colorBalance: 70,
  },
  {
    id: "mvv-maastricht",
    name: "MVV Maastricht",
    country: "Netherlands",
    league: "KKD",
    logoUrl: "/logos/netherlands/kkd/mvv-maastricht.png",
    primaryColor: "#C8102E",
    secondaryColor: "#FFFFFF",
    colorBalance: 72,
  },
  {
    id: "rkc-waalwijk",
    name: "RKC Waalwijk",
    country: "Netherlands",
    league: "KKD",
    logoUrl: "/logos/netherlands/kkd/rkc-waalwijk.png",
    primaryColor: "#FFD200",
    secondaryColor: "#0057B8",
    colorBalance: 66,
  },
  {
    id: "roda-jc",
    name: "Roda JC",
    country: "Netherlands",
    league: "KKD",
    logoUrl: "/logos/netherlands/kkd/roda-jc.png",
    primaryColor: "#FFD200",
    secondaryColor: "#000000",
    colorBalance: 68,
    aliases: ["Roda JC Kerkrade"],
  },
  {
    id: "sc-cambuur",
    name: "SC Cambuur",
    country: "Netherlands",
    league: "KKD",
    logoUrl: "/logos/netherlands/kkd/sc-cambuur.png",
    primaryColor: "#FFD200",
    secondaryColor: "#0057B8",
    colorBalance: 66,
    aliases: ["Cambuur"],
  },
  {
    id: "top-oss",
    name: "TOP Oss",
    country: "Netherlands",
    league: "KKD",
    logoUrl: "/logos/netherlands/kkd/top-oss.png",
    primaryColor: "#D71920",
    secondaryColor: "#FFFFFF",
    colorBalance: 72,
  },
  {
    id: "vitesse",
    name: "Vitesse",
    country: "Netherlands",
    league: "KKD",
    logoUrl: "/logos/netherlands/kkd/vitesse.png",
    primaryColor: "#FFD200",
    secondaryColor: "#000000",
    colorBalance: 68,
  },
  {
    id: "vvv-venlo",
    name: "VVV-Venlo",
    country: "Netherlands",
    league: "KKD",
    logoUrl: "/logos/netherlands/kkd/vvv-venlo.png",
    primaryColor: "#FFD200",
    secondaryColor: "#000000",
    colorBalance: 68,
  },
  {
    id: "willem-ii",
    name: "Willem II",
    country: "Netherlands",
    league: "KKD",
    logoUrl: "/logos/netherlands/kkd/willem-ii.png",
    primaryColor: "#D71920",
    secondaryColor: "#0057B8",
    colorBalance: 62,
    aliases: ["Willem II Tilburg"],
  },
/* =========================
   ENGLAND — PREMIER LEAGUE
   ========================= */

{
  id: "arsenal",
  name: "Arsenal",
  country: "England",
  league: "Premier League",
  logoUrl: "/logos/england/premier-league/arsenal.png",
  primaryColor: "#EF0107",
  secondaryColor: "#FFFFFF",
  colorBalance: 74,
  aliases: ["Arsenal FC"],
  shirtImageUrl: "/shirts/england/premier-league/arsenal.png",
},
{
  id: "aston-villa",
  name: "Aston Villa",
  country: "England",
  league: "Premier League",
  logoUrl: "/logos/england/premier-league/aston-villa.png",
  primaryColor: "#670E36",
  secondaryColor: "#95BFE5",
  colorBalance: 68,
  aliases: ["AVFC"],
  shirtImageUrl: "/shirts/england/premier-league/aston-villa.png",
},
{
  id: "bournemouth",
  name: "Bournemouth",
  country: "England",
  league: "Premier League",
  logoUrl: "/logos/england/premier-league/bournemouth.png",
  primaryColor: "#DA291C",
  secondaryColor: "#000000",
  colorBalance: 64,
  aliases: ["AFC Bournemouth"],
  shirtImageUrl: "/shirts/england/premier-league/bournemouth.png",
},
{
  id: "brentford",
  name: "Brentford",
  country: "England",
  league: "Premier League",
  logoUrl: "/logos/england/premier-league/brentford.png",
  primaryColor: "#E30613",
  secondaryColor: "#FFFFFF",
  colorBalance: 70,
  aliases: ["Brentford FC"],
  shirtImageUrl: "/shirts/england/premier-league/brentford.png",
},
{
  id: "brighton",
  name: "Brighton & Hove Albion",
  country: "England",
  league: "Premier League",
  logoUrl: "/logos/england/premier-league/brighton.png",
  primaryColor: "#0057B8",
  secondaryColor: "#FFFFFF",
  colorBalance: 72,
  aliases: ["Brighton"],
  shirtImageUrl: "/shirts/england/premier-league/brighton.png",
},
{
  id: "burnley",
  name: "Burnley",
  country: "England",
  league: "Premier League",
  logoUrl: "/logos/england/premier-league/burnley.png",
  primaryColor: "#6C1D45",
  secondaryColor: "#99D6EA",
  colorBalance: 66,
  aliases: ["Burnley FC"],
  shirtImageUrl: "/shirts/england/premier-league/burnley.png",
},
{
  id: "chelsea",
  name: "Chelsea",
  country: "England",
  league: "Premier League",
  logoUrl: "/logos/england/premier-league/chelsea.png",
  primaryColor: "#034694",
  secondaryColor: "#FFFFFF",
  colorBalance: 76,
  aliases: ["Chelsea FC"],
  shirtImageUrl: "/shirts/england/premier-league/chelsea.png",
},
{
  id: "crystal-palace",
  name: "Crystal Palace",
  country: "England",
  league: "Premier League",
  logoUrl: "/logos/england/premier-league/crystal-palace.png",
  primaryColor: "#1B458F",
  secondaryColor: "#C4122E",
  colorBalance: 60,
  aliases: ["Palace"],
  shirtImageUrl: "/shirts/england/premier-league/crystal-palace.png",
},
{
  id: "everton",
  name: "Everton",
  country: "England",
  league: "Premier League",
  logoUrl: "/logos/england/premier-league/everton.png",
  primaryColor: "#003399",
  secondaryColor: "#FFFFFF",
  colorBalance: 76,
  aliases: ["Everton FC"],
  shirtImageUrl: "/shirts/england/premier-league/everton.png",
},
{
  id: "fulham",
  name: "Fulham",
  country: "England",
  league: "Premier League",
  logoUrl: "/logos/england/premier-league/fulham.png",
  primaryColor: "#FFFFFF",
  secondaryColor: "#000000",
  colorBalance: 68,
  aliases: ["Fulham FC"],
  shirtImageUrl: "/shirts/england/premier-league/fulham.png",
},
{
  id: "leeds",
  name: "Leeds United",
  country: "England",
  league: "Premier League",
  logoUrl: "/logos/england/premier-league/leeds.png",
  primaryColor: "#FFFFFF",
  secondaryColor: "#1D428A",
  colorBalance: 70,
  aliases: ["Leeds"],
  shirtImageUrl: "/shirts/england/premier-league/leeds.png",
},
{
  id: "liverpool",
  name: "Liverpool",
  country: "England",
  league: "Premier League",
  logoUrl: "/logos/england/premier-league/liverpool.png",
  primaryColor: "#C8102E",
  secondaryColor: "#00B2A9",
  colorBalance: 78,
  aliases: ["Liverpool FC"],
  shirtImageUrl: "/shirts/england/premier-league/liverpool.png",
},
{
  id: "man-city",
  name: "Manchester City",
  country: "England",
  league: "Premier League",
  logoUrl: "/logos/england/premier-league/manchester-city.png",
  primaryColor: "#6CABDD",
  secondaryColor: "#1C2C5B",
  colorBalance: 72,
  aliases: ["Man City"],
  shirtImageUrl: "/shirts/england/premier-league/man-city.png",
},
{
  id: "man-united",
  name: "Manchester United",
  country: "England",
  league: "Premier League",
  logoUrl: "/logos/england/premier-league/manchester-united.png",
  primaryColor: "#DA291C",
  secondaryColor: "#FFFFFF",
  colorBalance: 74,
  aliases: ["Man United"],
  shirtImageUrl: "/shirts/england/premier-league/man-united.png",
},
{
  id: "newcastle",
  name: "Newcastle United",
  country: "England",
  league: "Premier League",
  logoUrl: "/logos/england/premier-league/newcastle.png",
  primaryColor: "#000000",
  secondaryColor: "#FFFFFF",
  colorBalance: 62,
  aliases: ["Newcastle"],
  shirtImageUrl: "/shirts/england/premier-league/newcastle.png",
},
{
  id: "nottingham-forest",
  name: "Nottingham Forest",
  country: "England",
  league: "Premier League",
  logoUrl: "/logos/england/premier-league/nottingham-forest.png",
  primaryColor: "#DD0000",
  secondaryColor: "#FFFFFF",
  colorBalance: 74,
  aliases: ["Forest"],
  shirtImageUrl: "/shirts/england/premier-league/nottingham-forest.png",
},
{
  id: "sunderland",
  name: "Sunderland",
  country: "England",
  league: "Premier League",
  logoUrl: "/logos/england/premier-league/sunderland.png",
  primaryColor: "#EB172B",
  secondaryColor: "#FFFFFF",
  colorBalance: 70,
  aliases: ["Sunderland AFC"],
  shirtImageUrl: "/shirts/england/premier-league/sunderland.png",
},
{
  id: "tottenham",
  name: "Tottenham Hotspur",
  country: "England",
  league: "Premier League",
  logoUrl: "/logos/england/premier-league/tottenham.png",
  primaryColor: "#FFFFFF",
  secondaryColor: "#132257",
  colorBalance: 72,
  aliases: ["Spurs"],
  shirtImageUrl: "/shirts/england/premier-league/tottenham.png",
},
{
  id: "west-ham",
  name: "West Ham United",
  country: "England",
  league: "Premier League",
  logoUrl: "/logos/england/premier-league/west-ham.png",
  primaryColor: "#7A263A",
  secondaryColor: "#1BB1E7",
  colorBalance: 66,
  aliases: ["West Ham"],
  shirtImageUrl: "/shirts/england/premier-league/west-ham.png",
},
{
  id: "wolves",
  name: "Wolverhampton Wanderers",
  country: "England",
  league: "Premier League",
  logoUrl: "/logos/england/premier-league/wolves.png",
  primaryColor: "#FDB913",
  secondaryColor: "#231F20",
  colorBalance: 74,
  aliases: ["Wolves"],
  shirtImageUrl: "/shirts/england/premier-league/wolves.png",
},

/* =========================
   ENGLAND — CHAMPIONSHIP
   ========================= */

{
  id: "birmingham-city",
  name: "Birmingham City",
  country: "England",
  league: "Championship",
  logoUrl: "/logos/england/championship/birmingham-city.png",
  primaryColor: "#0046AE",
  secondaryColor: "#FFFFFF",
  colorBalance: 74,
  aliases: ["Birmingham"],
  shirtImageUrl: "/shirts/england/championship/birmingham-city.png",
},
{
  id: "blackburn",
  name: "Blackburn Rovers",
  country: "England",
  league: "Championship",
  logoUrl: "/logos/england/championship/blackburn.png",
  primaryColor: "#1F4FA3",
  secondaryColor: "#FFFFFF",
  colorBalance: 64,
  aliases: ["Blackburn"],
  shirtImageUrl: "/shirts/england/championship/blackburn.png",
},
{
  id: "bristol-city",
  name: "Bristol City",
  country: "England",
  league: "Championship",
  logoUrl: "/logos/england/championship/bristol-city.png",
  primaryColor: "#E31B23",
  secondaryColor: "#FFFFFF",
  colorBalance: 72,
  aliases: ["Bristol City FC"],
  shirtImageUrl: "/shirts/england/championship/bristol-city.png",
},
{
  id: "charlton",
  name: "Charlton Athletic",
  country: "England",
  league: "Championship",
  logoUrl: "/logos/england/championship/charlton.png",
  primaryColor: "#D71920",
  secondaryColor: "#FFFFFF",
  colorBalance: 72,
  aliases: ["Charlton"],
  shirtImageUrl: "/shirts/england/championship/charlton.png",
},
{
  id: "coventry",
  name: "Coventry City",
  country: "England",
  league: "Championship",
  logoUrl: "/logos/england/championship/coventry.png",
  primaryColor: "#6CABDD",
  secondaryColor: "#FFFFFF",
  colorBalance: 74,
  aliases: ["Coventry"],
  shirtImageUrl: "/shirts/england/championship/coventry.png",
},
{
  id: "derby-county",
  name: "Derby County",
  country: "England",
  league: "Championship",
  logoUrl: "/logos/england/championship/derby-county.png",
  primaryColor: "#FFFFFF",
  secondaryColor: "#000000",
  colorBalance: 66,
  aliases: ["Derby"],
  shirtImageUrl: "/shirts/england/championship/derby-county.png",
},
{
  id: "hull-city",
  name: "Hull City",
  country: "England",
  league: "Championship",
  logoUrl: "/logos/england/championship/hull-city.png",
  primaryColor: "#F28C28",
  secondaryColor: "#000000",
  colorBalance: 68,
  aliases: ["Hull"],
  shirtImageUrl: "/shirts/england/championship/hull-city.png",
},
{
  id: "ipswich",
  name: "Ipswich Town",
  country: "England",
  league: "Championship",
  logoUrl: "/logos/england/championship/ipswich.png",
  primaryColor: "#0057B8",
  secondaryColor: "#FFFFFF",
  colorBalance: 72,
  aliases: ["Ipswich"],
  shirtImageUrl: "/shirts/england/championship/ipswich.png",
},
{
  id: "leicester",
  name: "Leicester City",
  country: "England",
  league: "Championship",
  logoUrl: "/logos/england/championship/leicester.png",
  primaryColor: "#003090",
  secondaryColor: "#FFFFFF",
  colorBalance: 76,
  aliases: ["Leicester"],
  shirtImageUrl: "/shirts/england/championship/leicester.png",
},
{
  id: "middlesbrough",
  name: "Middlesbrough",
  country: "England",
  league: "Championship",
  logoUrl: "/logos/england/championship/middlesbrough.png",
  primaryColor: "#D71920",
  secondaryColor: "#FFFFFF",
  colorBalance: 74,
  aliases: ["Boro"],
  shirtImageUrl: "/shirts/england/championship/middlesbrough.png",
},
{
  id: "millwall",
  name: "Millwall",
  country: "England",
  league: "Championship",
  logoUrl: "/logos/england/championship/millwall.png",
  primaryColor: "#002E5D",
  secondaryColor: "#FFFFFF",
  colorBalance: 72,
  aliases: ["Millwall FC"],
  shirtImageUrl: "/shirts/england/championship/millwall.png",
},
{
  id: "norwich",
  name: "Norwich City",
  country: "England",
  league: "Championship",
  logoUrl: "/logos/england/championship/norwich.png",
  primaryColor: "#FFF200",
  secondaryColor: "#00A650",
  colorBalance: 66,
  aliases: ["Norwich"],
  shirtImageUrl: "/shirts/england/championship/norwich.png",
},
{
  id: "oxford-united",
  name: "Oxford United",
  country: "England",
  league: "Championship",
  logoUrl: "/logos/england/championship/oxford-united.png",
  primaryColor: "#FFD200",
  secondaryColor: "#002147",
  colorBalance: 70,
  aliases: ["Oxford"],
  shirtImageUrl: "/shirts/england/championship/oxford-united.png",
},
{
  id: "portsmouth",
  name: "Portsmouth",
  country: "England",
  league: "Championship",
  logoUrl: "/logos/england/championship/portsmouth.png",
  primaryColor: "#003087",
  secondaryColor: "#FFFFFF",
  colorBalance: 74,
  aliases: ["Pompey"],
  shirtImageUrl: "/shirts/england/championship/portsmouth.png",
},
{
  id: "preston",
  name: "Preston North End",
  country: "England",
  league: "Championship",
  logoUrl: "/logos/england/championship/preston.png",
  primaryColor: "#FFFFFF",
  secondaryColor: "#003366",
  colorBalance: 66,
  aliases: ["Preston"],
  shirtImageUrl: "/shirts/england/championship/preston.png",
},
{
  id: "qpr",
  name: "Queens Park Rangers",
  country: "England",
  league: "Championship",
  logoUrl: "/logos/england/championship/qpr.png",
  primaryColor: "#1B458F",
  secondaryColor: "#FFFFFF",
  colorBalance: 64,
  aliases: ["QPR"],
  shirtImageUrl: "/shirts/england/championship/qpr.png",
},
{
  id: "sheffield-united",
  name: "Sheffield United",
  country: "England",
  league: "Championship",
  logoUrl: "/logos/england/championship/sheffield-united.png",
  primaryColor: "#EE2737",
  secondaryColor: "#000000",
  colorBalance: 68,
  aliases: ["Sheff United"],
  shirtImageUrl: "/shirts/england/championship/sheffield-united.png",
},
{
  id: "sheffield-wednesday",
  name: "Sheffield Wednesday",
  country: "England",
  league: "Championship",
  logoUrl: "/logos/england/championship/sheffield-wednesday.png",
  primaryColor: "#0057B8",
  secondaryColor: "#FFFFFF",
  colorBalance: 68,
  aliases: ["Sheff Wednesday"],
  shirtImageUrl: "/shirts/england/championship/sheffield-wednesday.png",
},
{
  id: "southampton",
  name: "Southampton",
  country: "England",
  league: "Championship",
  logoUrl: "/logos/england/championship/southampton.png",
  primaryColor: "#D71920",
  secondaryColor: "#FFFFFF",
  colorBalance: 70,
  aliases: ["Saints"],
  shirtImageUrl: "/shirts/england/championship/southampton.png",
},
{
  id: "stoke-city",
  name: "Stoke City",
  country: "England",
  league: "Championship",
  logoUrl: "/logos/england/championship/stoke-city.png",
  primaryColor: "#E03A3E",
  secondaryColor: "#FFFFFF",
  colorBalance: 70,
  aliases: ["Stoke"],
  shirtImageUrl: "/shirts/england/championship/stoke-city.png",
},
{
  id: "swansea",
  name: "Swansea City",
  country: "England",
  league: "Championship",
  logoUrl: "/logos/england/championship/swansea.png",
  primaryColor: "#FFFFFF",
  secondaryColor: "#000000",
  colorBalance: 68,
  aliases: ["Swansea"],
  shirtImageUrl: "/shirts/england/championship/swansea.png",
},
{
  id: "watford",
  name: "Watford",
  country: "England",
  league: "Championship",
  logoUrl: "/logos/england/championship/watford.png",
  primaryColor: "#FBEE23",
  secondaryColor: "#ED2127",
  colorBalance: 66,
  aliases: ["Watford FC"],
  shirtImageUrl: "/shirts/england/championship/watford.png",
},
{
  id: "west-brom",
  name: "West Bromwich Albion",
  country: "England",
  league: "Championship",
  logoUrl: "/logos/england/championship/west-brom.png",
  primaryColor: "#122F67",
  secondaryColor: "#FFFFFF",
  colorBalance: 66,
  aliases: ["West Brom"],
  shirtImageUrl: "/shirts/england/championship/west-brom.png",
},
{
  id: "wrexham",
  name: "Wrexham",
  country: "England",
  league: "Championship",
  logoUrl: "/logos/england/championship/wrexham.png",
  primaryColor: "#E31B23",
  secondaryColor: "#FFFFFF",
  colorBalance: 72,
  aliases: ["Wrexham AFC"],
  shirtImageUrl: "/shirts/england/championship/wrexham.png",
},
/* =========================
   ITALY — SERIE A
   ========================= */

{
  id: "atalanta",
  name: "Atalanta",
  country: "Italy",
  league: "Serie A",
  logoUrl: "/logos/italy/serie-a/atalanta.png",
  primaryColor: "#00529F",
  secondaryColor: "#000000",
  colorBalance: 58,
  aliases: ["Atalanta BC"],
  shirtImageUrl: "/shirts/italy/serie-a/atalanta.png",
},
{
  id: "bologna",
  name: "Bologna",
  country: "Italy",
  league: "Serie A",
  logoUrl: "/logos/italy/serie-a/bologna.png",
  primaryColor: "#9E1B32",
  secondaryColor: "#1D4E89",
  colorBalance: 58,
  aliases: ["Bologna FC", "Bologna FC 1909"],
  shirtImageUrl: "/shirts/italy/serie-a/bologna.png",
},
{
  id: "cagliari",
  name: "Cagliari",
  country: "Italy",
  league: "Serie A",
  logoUrl: "/logos/italy/serie-a/cagliari.png",
  primaryColor: "#C8102E",
  secondaryColor: "#003B7A",
  colorBalance: 56,
  aliases: ["Cagliari Calcio"],
  shirtImageUrl: "/shirts/italy/serie-a/cagliari.png",
},
{
  id: "como",
  name: "Como",
  country: "Italy",
  league: "Serie A",
  logoUrl: "/logos/italy/serie-a/como.png",
  primaryColor: "#0054A6",
  secondaryColor: "#FFFFFF",
  colorBalance: 74,
  aliases: ["Como 1907"],
  shirtImageUrl: "/shirts/italy/serie-a/como.png",
},
{
  id: "cremonese",
  name: "Cremonese",
  country: "Italy",
  league: "Serie A",
  logoUrl: "/logos/italy/serie-a/cremonese.png",
  primaryColor: "#A6192E",
  secondaryColor: "#8E8C89",
  colorBalance: 66,
  aliases: ["US Cremonese"],
  shirtImageUrl: "/shirts/italy/serie-a/cremonese.png",
},
{
  id: "fiorentina",
  name: "Fiorentina",
  country: "Italy",
  league: "Serie A",
  logoUrl: "/logos/italy/serie-a/fiorentina.png",
  primaryColor: "#5B2C83",
  secondaryColor: "#FFFFFF",
  colorBalance: 76,
  aliases: ["ACF Fiorentina"],
  shirtImageUrl: "/shirts/italy/serie-a/fiorentina.png",
},
{
  id: "genoa",
  name: "Genoa",
  country: "Italy",
  league: "Serie A",
  logoUrl: "/logos/italy/serie-a/genoa.png",
  primaryColor: "#A6192E",
  secondaryColor: "#003087",
  colorBalance: 54,
  aliases: ["Genoa CFC"],
  shirtImageUrl: "/shirts/italy/serie-a/genoa.png",
},
{
  id: "hellas-verona",
  name: "Hellas Verona",
  country: "Italy",
  league: "Serie A",
  logoUrl: "/logos/italy/serie-a/hellas-verona.png",
  primaryColor: "#FFD100",
  secondaryColor: "#1E4FA1",
  colorBalance: 54,
  aliases: ["Verona", "Hellas"],
  shirtImageUrl: "/shirts/italy/serie-a/hellas-verona.png",
},
{
  id: "inter",
  name: "Inter",
  country: "Italy",
  league: "Serie A",
  logoUrl: "/logos/italy/serie-a/inter.png",
  primaryColor: "#00529F",
  secondaryColor: "#000000",
  colorBalance: 56,
  aliases: ["Internazionale", "Inter Milan"],
  shirtImageUrl: "/shirts/italy/serie-a/inter.png",
},
{
  id: "juventus",
  name: "Juventus",
  country: "Italy",
  league: "Serie A",
  logoUrl: "/logos/italy/serie-a/juventus.png",
  primaryColor: "#FFFFFF",
  secondaryColor: "#000000",
  colorBalance: 60,
  aliases: ["Juve"],
  shirtImageUrl: "/shirts/italy/serie-a/juventus.png",
},
{
  id: "lazio",
  name: "Lazio",
  country: "Italy",
  league: "Serie A",
  logoUrl: "/logos/italy/serie-a/lazio.png",
  primaryColor: "#9BCBEB",
  secondaryColor: "#FFFFFF",
  colorBalance: 72,
  aliases: ["SS Lazio"],
  shirtImageUrl: "/shirts/italy/serie-a/lazio.png",
},
{
  id: "lecce",
  name: "Lecce",
  country: "Italy",
  league: "Serie A",
  logoUrl: "/logos/italy/serie-a/lecce.png",
  primaryColor: "#F5C400",
  secondaryColor: "#C8102E",
  colorBalance: 58,
  aliases: ["US Lecce"],
  shirtImageUrl: "/shirts/italy/serie-a/lecce.png",
},
{
  id: "milan",
  name: "Milan",
  country: "Italy",
  league: "Serie A",
  logoUrl: "/logos/italy/serie-a/milan.png",
  primaryColor: "#D71920",
  secondaryColor: "#000000",
  colorBalance: 56,
  aliases: ["AC Milan"],
  shirtImageUrl: "/shirts/italy/serie-a/milan.png",
},
{
  id: "napoli",
  name: "Napoli",
  country: "Italy",
  league: "Serie A",
  logoUrl: "/logos/italy/serie-a/napoli.png",
  primaryColor: "#0085CA",
  secondaryColor: "#FFFFFF",
  colorBalance: 78,
  aliases: ["SSC Napoli"],
  shirtImageUrl: "/shirts/italy/serie-a/napoli.png",
},
{
  id: "parma",
  name: "Parma",
  country: "Italy",
  league: "Serie A",
  logoUrl: "/logos/italy/serie-a/parma.png",
  primaryColor: "#FFD100",
  secondaryColor: "#1F2A44",
  colorBalance: 52,
  aliases: ["Parma Calcio"],
  shirtImageUrl: "/shirts/italy/serie-a/parma.png",
},
{
  id: "pisa",
  name: "Pisa",
  country: "Italy",
  league: "Serie A",
  logoUrl: "/logos/italy/serie-a/pisa.png",
  primaryColor: "#0F172A",
  secondaryColor: "#1D4E89",
  colorBalance: 68,
  aliases: ["Pisa SC"],
  shirtImageUrl: "/shirts/italy/serie-a/pisa.png",
},
{
  id: "roma",
  name: "Roma",
  country: "Italy",
  league: "Serie A",
  logoUrl: "/logos/italy/serie-a/roma.png",
  primaryColor: "#8E1F2F",
  secondaryColor: "#F7B500",
  colorBalance: 62,
  aliases: ["AS Roma"],
  shirtImageUrl: "/shirts/italy/serie-a/roma.png",
},
{
  id: "sassuolo",
  name: "Sassuolo",
  country: "Italy",
  league: "Serie A",
  logoUrl: "/logos/italy/serie-a/sassuolo.png",
  primaryColor: "#00A651",
  secondaryColor: "#000000",
  colorBalance: 64,
  aliases: ["US Sassuolo", "Sassuolo Calcio"],
  shirtImageUrl: "/shirts/italy/serie-a/sassuolo.png",
},
{
  id: "torino",
  name: "Torino",
  country: "Italy",
  league: "Serie A",
  logoUrl: "/logos/italy/serie-a/torino.png",
  primaryColor: "#7B1E3A",
  secondaryColor: "#FFFFFF",
  colorBalance: 76,
  aliases: ["Torino FC"],
  shirtImageUrl: "/shirts/italy/serie-a/torino.png",
},
{
  id: "udinese",
  name: "Udinese",
  country: "Italy",
  league: "Serie A",
  logoUrl: "/logos/italy/serie-a/udinese.png",
  primaryColor: "#000000",
  secondaryColor: "#FFFFFF",
  colorBalance: 62,
  aliases: ["Udinese Calcio"],
  shirtImageUrl: "/shirts/italy/serie-a/udinese.png",
},

/* =========================
   ITALY — SERIE B
   ========================= */

{
  id: "avellino",
  name: "Avellino",
  country: "Italy",
  league: "Serie B",
  logoUrl: "/logos/italy/serie-b/avellino.png",
  primaryColor: "#00853F",
  secondaryColor: "#FFFFFF",
  colorBalance: 70,
  aliases: ["US Avellino"],
  shirtImageUrl: "/shirts/italy/serie-b/avellino.png",
},
{
  id: "bari",
  name: "Bari",
  country: "Italy",
  league: "Serie B",
  logoUrl: "/logos/italy/serie-b/bari.png",
  primaryColor: "#D71920",
  secondaryColor: "#FFFFFF",
  colorBalance: 72,
  aliases: ["SSC Bari"],
  shirtImageUrl: "/shirts/italy/serie-b/bari.png",
},
{
  id: "carrarese",
  name: "Carrarese",
  country: "Italy",
  league: "Serie B",
  logoUrl: "/logos/italy/serie-b/carrarese.png",
  primaryColor: "#1E5AA8",
  secondaryColor: "#FFD200",
  colorBalance: 64,
  aliases: ["Carrarese Calcio"],
  shirtImageUrl: "/shirts/italy/serie-b/carrarese.png",
},
{
  id: "catanzaro",
  name: "Catanzaro",
  country: "Italy",
  league: "Serie B",
  logoUrl: "/logos/italy/serie-b/catanzaro.png",
  primaryColor: "#D71920",
  secondaryColor: "#FFD200",
  colorBalance: 66,
  aliases: ["US Catanzaro 1929"],
  shirtImageUrl: "/shirts/italy/serie-b/catanzaro.png",
},
{
  id: "cesena",
  name: "Cesena",
  country: "Italy",
  league: "Serie B",
  logoUrl: "/logos/italy/serie-b/cesena.png",
  primaryColor: "#000000",
  secondaryColor: "#FFFFFF",
  colorBalance: 70,
  aliases: ["Cesena FC"],
  shirtImageUrl: "/shirts/italy/serie-b/cesena.png",
},
{
  id: "empoli",
  name: "Empoli",
  country: "Italy",
  league: "Serie B",
  logoUrl: "/logos/italy/serie-b/empoli.png",
  primaryColor: "#0057B8",
  secondaryColor: "#FFFFFF",
  colorBalance: 74,
  aliases: ["Empoli FC"],
  shirtImageUrl: "/shirts/italy/serie-b/empoli.png",
},
{
  id: "entella",
  name: "Entella",
  country: "Italy",
  league: "Serie B",
  logoUrl: "/logos/italy/serie-b/entella.png",
  primaryColor: "#1E5AA8",
  secondaryColor: "#FFFFFF",
  colorBalance: 72,
  aliases: ["Virtus Entella"],
  shirtImageUrl: "/shirts/italy/serie-b/entella.png",
},
{
  id: "frosinone",
  name: "Frosinone",
  country: "Italy",
  league: "Serie B",
  logoUrl: "/logos/italy/serie-b/frosinone.png",
  primaryColor: "#FFD200",
  secondaryColor: "#1E5AA8",
  colorBalance: 68,
  aliases: ["Frosinone Calcio"],
  shirtImageUrl: "/shirts/italy/serie-b/frosinone.png",
},
{
  id: "juve-stabia",
  name: "Juve Stabia",
  country: "Italy",
  league: "Serie B",
  logoUrl: "/logos/italy/serie-b/juve-stabia.png",
  primaryColor: "#FFD200",
  secondaryColor: "#1E3A8A",
  colorBalance: 68,
  aliases: ["SS Juve Stabia"],
  shirtImageUrl: "/shirts/italy/serie-b/juve-stabia.png",
},
{
  id: "mantova",
  name: "Mantova",
  country: "Italy",
  league: "Serie B",
  logoUrl: "/logos/italy/serie-b/mantova.png",
  primaryColor: "#D71920",
  secondaryColor: "#FFFFFF",
  colorBalance: 70,
  aliases: ["AC Mantova"],
  shirtImageUrl: "/shirts/italy/serie-b/mantova.png",
},
{
  id: "modena",
  name: "Modena",
  country: "Italy",
  league: "Serie B",
  logoUrl: "/logos/italy/serie-b/modena.png",
  primaryColor: "#FFD200",
  secondaryColor: "#1E3A8A",
  colorBalance: 66,
  aliases: ["Modena FC"],
  shirtImageUrl: "/shirts/italy/serie-b/modena.png",
},
{
  id: "monza",
  name: "Monza",
  country: "Italy",
  league: "Serie B",
  logoUrl: "/logos/italy/serie-b/monza.png",
  primaryColor: "#D71920",
  secondaryColor: "#FFFFFF",
  colorBalance: 72,
  aliases: ["AC Monza"],
  shirtImageUrl: "/shirts/italy/serie-b/monza.png",
},
{
  id: "padova",
  name: "Padova",
  country: "Italy",
  league: "Serie B",
  logoUrl: "/logos/italy/serie-b/padova.png",
  primaryColor: "#D71920",
  secondaryColor: "#FFFFFF",
  colorBalance: 70,
  aliases: ["Calcio Padova"],
  shirtImageUrl: "/shirts/italy/serie-b/padova.png",
},
{
  id: "palermo",
  name: "Palermo",
  country: "Italy",
  league: "Serie B",
  logoUrl: "/logos/italy/serie-b/palermo.png",
  primaryColor: "#F4A6C1",
  secondaryColor: "#000000",
  colorBalance: 68,
  aliases: ["Palermo FC"],
  shirtImageUrl: "/shirts/italy/serie-b/palermo.png",
},
{
  id: "pescara",
  name: "Pescara",
  country: "Italy",
  league: "Serie B",
  logoUrl: "/logos/italy/serie-b/pescara.png",
  primaryColor: "#0057B8",
  secondaryColor: "#FFFFFF",
  colorBalance: 72,
  aliases: ["Delfino Pescara"],
  shirtImageUrl: "/shirts/italy/serie-b/pescara.png",
},
{
  id: "reggiana",
  name: "Reggiana",
  country: "Italy",
  league: "Serie B",
  logoUrl: "/logos/italy/serie-b/reggiana.png",
  primaryColor: "#D71920",
  secondaryColor: "#FFD200",
  colorBalance: 66,
  aliases: ["AC Reggiana 1919"],
  shirtImageUrl: "/shirts/italy/serie-b/reggiana.png",
},
{
  id: "sampdoria",
  name: "Sampdoria",
  country: "Italy",
  league: "Serie B",
  logoUrl: "/logos/italy/serie-b/sampdoria.png",
  primaryColor: "#0057B8",
  secondaryColor: "#FFFFFF",
  colorBalance: 64,
  aliases: ["UC Sampdoria"],
  shirtImageUrl: "/shirts/italy/serie-b/sampdoria.png",
},
{
  id: "spezia",
  name: "Spezia",
  country: "Italy",
  league: "Serie B",
  logoUrl: "/logos/italy/serie-b/spezia.png",
  primaryColor: "#000000",
  secondaryColor: "#FFFFFF",
  colorBalance: 72,
  aliases: ["Spezia Calcio"],
  shirtImageUrl: "/shirts/italy/serie-b/spezia.png",
},
{
  id: "sudtirol",
  name: "Südtirol",
  country: "Italy",
  league: "Serie B",
  logoUrl: "/logos/italy/serie-b/sudtirol.png",
  primaryColor: "#D71920",
  secondaryColor: "#FFFFFF",
  colorBalance: 68,
  aliases: ["FC Südtirol"],
  shirtImageUrl: "/shirts/italy/serie-b/sudtirol.png",
},
{
  id: "venezia",
  name: "Venezia",
  country: "Italy",
  league: "Serie B",
  logoUrl: "/logos/italy/serie-b/venezia.png",
  primaryColor: "#0B3D2E",
  secondaryColor: "#F2C94C",
  colorBalance: 64,
  aliases: ["Venezia FC"],
  shirtImageUrl: "/shirts/italy/serie-b/venezia.png",
},

   /* =========================
   GERMANY — BUNDESLIGA
   ========================= */

{
  id: "augsburg",
  name: "Augsburg",
  country: "Germany",
  league: "Bundesliga",
  logoUrl: "/logos/germany/bundesliga/augsburg.png",
  primaryColor: "#D71920",
  secondaryColor: "#00853F",
  colorBalance: 65,
  aliases: ["FC Augsburg"],
  shirtImageUrl: "/shirts/germany/bundesliga/augsburg.png",
},
{
  id: "bayern",
  name: "Bayern",
  country: "Germany",
  league: "Bundesliga",
  logoUrl: "/logos/germany/bundesliga/bayern.png",
  primaryColor: "#DC052D",
  secondaryColor: "#0066B2",
  colorBalance: 72,
  aliases: ["FC Bayern München", "Bayern Munich"],
  shirtImageUrl: "/shirts/germany/bundesliga/bayern.png",
},
{
  id: "borussia-dortmund",
  name: "Dortmund",
  country: "Germany",
  league: "Bundesliga",
  logoUrl: "/logos/germany/bundesliga/borussia-dortmund.png",
  primaryColor: "#FDE100",
  secondaryColor: "#000000",
  colorBalance: 74,
  aliases: ["Borussia Dortmund", "BVB"],
  shirtImageUrl: "/shirts/germany/bundesliga/borussia-dortmund.png",
},
{
  id: "borussia-monchengladbach",
  name: "Mönchengladbach",
  country: "Germany",
  league: "Bundesliga",
  logoUrl: "/logos/germany/bundesliga/borussia-monchengladbach.png",
  primaryColor: "#000000",
  secondaryColor: "#FFFFFF",
  colorBalance: 70,
  aliases: ["Borussia Mönchengladbach", "Gladbach"],
  shirtImageUrl: "/shirts/germany/bundesliga/borussia-monchengladbach.png",
},
{
  id: "eintracht-frankfurt",
  name: "Frankfurt",
  country: "Germany",
  league: "Bundesliga",
  logoUrl: "/logos/germany/bundesliga/eintracht-frankfurt.png",
  primaryColor: "#000000",
  secondaryColor: "#D71920",
  colorBalance: 68,
  aliases: ["Eintracht Frankfurt"],
  shirtImageUrl: "/shirts/germany/bundesliga/eintracht-frankfurt.png",
},
{
  id: "freiburg",
  name: "Freiburg",
  country: "Germany",
  league: "Bundesliga",
  logoUrl: "/logos/germany/bundesliga/freiburg.png",
  primaryColor: "#D71920",
  secondaryColor: "#000000",
  colorBalance: 66,
  aliases: ["SC Freiburg"],
  shirtImageUrl: "/shirts/germany/bundesliga/freiburg.png",
},
{
  id: "heidenheim",
  name: "Heidenheim",
  country: "Germany",
  league: "Bundesliga",
  logoUrl: "/logos/germany/bundesliga/heidenheim.png",
  primaryColor: "#D71920",
  secondaryColor: "#003A8F",
  colorBalance: 64,
  aliases: ["1. FC Heidenheim"],
  shirtImageUrl: "/shirts/germany/bundesliga/heidenheim.png",
},
{
  id: "hoffenheim",
  name: "Hoffenheim",
  country: "Germany",
  league: "Bundesliga",
  logoUrl: "/logos/germany/bundesliga/hoffenheim.png",
  primaryColor: "#0057B8",
  secondaryColor: "#FFFFFF",
  colorBalance: 72,
  aliases: ["TSG Hoffenheim"],
  shirtImageUrl: "/shirts/germany/bundesliga/hoffenheim.png",
},
{
  id: "koln",
  name: "Köln",
  country: "Germany",
  league: "Bundesliga",
  logoUrl: "/logos/germany/bundesliga/koln.png",
  primaryColor: "#D71920",
  secondaryColor: "#FFFFFF",
  colorBalance: 70,
  aliases: ["1. FC Köln", "FC Cologne"],
  shirtImageUrl: "/shirts/germany/bundesliga/koln.png",
},
{
  id: "leverkusen",
  name: "Leverkusen",
  country: "Germany",
  league: "Bundesliga",
  logoUrl: "/logos/germany/bundesliga/leverkusen.png",
  primaryColor: "#000000",
  secondaryColor: "#D71920",
  colorBalance: 68,
  aliases: ["Bayer 04 Leverkusen"],
  shirtImageUrl: "/shirts/germany/bundesliga/leverkusen.png",
},
{
  id: "mainz",
  name: "Mainz",
  country: "Germany",
  league: "Bundesliga",
  logoUrl: "/logos/germany/bundesliga/mainz-05.png",
  primaryColor: "#D71920",
  secondaryColor: "#FFFFFF",
  colorBalance: 70,
  aliases: ["1. FSV Mainz 05"],
  shirtImageUrl: "/shirts/germany/bundesliga/mainz.png",
},
{
  id: "rb-leipzig",
  name: "Leipzig",
  country: "Germany",
  league: "Bundesliga",
  logoUrl: "/logos/germany/bundesliga/rb-leipzig.png",
  primaryColor: "#FFFFFF",
  secondaryColor: "#D71920",
  colorBalance: 58,
  aliases: ["RB Leipzig"],
  shirtImageUrl: "/shirts/germany/bundesliga/rb-leipzig.png",
},
{
  id: "st-pauli",
  name: "St. Pauli",
  country: "Germany",
  league: "Bundesliga",
  logoUrl: "/logos/germany/bundesliga/st-pauli.png",
  primaryColor: "#4A2C2A",
  secondaryColor: "#FFFFFF",
  colorBalance: 66,
  aliases: ["FC St. Pauli"],
  shirtImageUrl: "/shirts/germany/bundesliga/st-pauli.png",
},
{
  id: "stuttgart",
  name: "Stuttgart",
  country: "Germany",
  league: "Bundesliga",
  logoUrl: "/logos/germany/bundesliga/stuttgart.png",
  primaryColor: "#FFFFFF",
  secondaryColor: "#D71920",
  colorBalance: 60,
  aliases: ["VfB Stuttgart"],
  shirtImageUrl: "/shirts/germany/bundesliga/stuttgart.png",
},
{
  id: "union-berlin",
  name: "Union Berlin",
  country: "Germany",
  league: "Bundesliga",
  logoUrl: "/logos/germany/bundesliga/union-berlin.png",
  primaryColor: "#D71920",
  secondaryColor: "#F1C40F",
  colorBalance: 68,
  aliases: ["1. FC Union Berlin"],
  shirtImageUrl: "/shirts/germany/bundesliga/union-berlin.png",
},
{
  id: "vfl-wolfsburg",
  name: "Wolfsburg",
  country: "Germany",
  league: "Bundesliga",
  logoUrl: "/logos/germany/bundesliga/vfl-wolfsburg.png",
  primaryColor: "#65B32E",
  secondaryColor: "#FFFFFF",
  colorBalance: 70,
  aliases: ["VfL Wolfsburg"],
  shirtImageUrl: "/shirts/germany/bundesliga/vfl-wolfsburg.png",
},
{
  id: "werder-bremen",
  name: "Werder Bremen",
  country: "Germany",
  league: "Bundesliga",
  logoUrl: "/logos/germany/bundesliga/werder-bremen.png",
  primaryColor: "#00853F",
  secondaryColor: "#FFFFFF",
  colorBalance: 72,
  aliases: ["SV Werder Bremen"],
  shirtImageUrl: "/shirts/germany/bundesliga/werder-bremen.png",
},
{
  id: "hamburger-sv",
  name: "Hamburg",
  country: "Germany",
  league: "Bundesliga",
  logoUrl: "/logos/germany/bundesliga/hsv.png",
  primaryColor: "#0057B8",
  secondaryColor: "#FFFFFF",
  colorBalance: 68,
  aliases: ["Hamburger SV", "HSV"],
  shirtImageUrl: "/shirts/germany/bundesliga/hamburger-sv.png",
},

/* =========================
   GERMANY — 2. BUNDESLIGA
   ========================= */

{
  id: "arminia-bielefeld",
  name: "Arminia",
  country: "Germany",
  league: "2. Bundesliga",
  logoUrl: "/logos/germany/2-bundesliga/arminia-bielefeld.png",
  primaryColor: "#003A8F",
  secondaryColor: "#000000",
  colorBalance: 68,
  aliases: ["Arminia Bielefeld"],
  shirtImageUrl: "/shirts/germany/2-bundesliga/arminia-bielefeld.png",
},
{
  id: "bochum",
  name: "Bochum",
  country: "Germany",
  league: "2. Bundesliga",
  logoUrl: "/logos/germany/2-bundesliga/bochum.png",
  primaryColor: "#0057B8",
  secondaryColor: "#FFFFFF",
  colorBalance: 72,
  aliases: ["VfL Bochum"],
  shirtImageUrl: "/shirts/germany/2-bundesliga/bochum.png",
},
{
  id: "braunschweig",
  name: "Braunschweig",
  country: "Germany",
  league: "2. Bundesliga",
  logoUrl: "/logos/germany/2-bundesliga/braunschweig.png",
  primaryColor: "#FDB913",
  secondaryColor: "#1E3A8A",
  colorBalance: 64,
  aliases: ["Eintracht Braunschweig"],
  shirtImageUrl: "/shirts/germany/2-bundesliga/braunschweig.png",
},
{
  id: "darmstadt",
  name: "Darmstadt",
  country: "Germany",
  league: "2. Bundesliga",
  logoUrl: "/logos/germany/2-bundesliga/darmstadt.png",
  primaryColor: "#0057B8",
  secondaryColor: "#FFFFFF",
  colorBalance: 70,
  aliases: ["SV Darmstadt 98"],
  shirtImageUrl: "/shirts/germany/2-bundesliga/darmstadt.png",
},
{
  id: "dynamo-dresden",
  name: "Dresden",
  country: "Germany",
  league: "2. Bundesliga",
  logoUrl: "/logos/germany/2-bundesliga/dynamo-dresden.png",
  primaryColor: "#FFD200",
  secondaryColor: "#7A1E1E",
  colorBalance: 66,
  aliases: ["Dynamo Dresden"],
  shirtImageUrl: "/shirts/germany/2-bundesliga/dynamo-dresden.png",
},
{
  id: "elversberg",
  name: "Elversberg",
  country: "Germany",
  league: "2. Bundesliga",
  logoUrl: "/logos/germany/2-bundesliga/elversberg.png",
  primaryColor: "#000000",
  secondaryColor: "#FFFFFF",
  colorBalance: 68,
  aliases: ["SV Elversberg"],
  shirtImageUrl: "/shirts/germany/2-bundesliga/elversberg.png",
},
{
  id: "fortuna-dusseldorf",
  name: "Düsseldorf",
  country: "Germany",
  league: "2. Bundesliga",
  logoUrl: "/logos/germany/2-bundesliga/fortuna-dusseldorf.png",
  primaryColor: "#E32219",
  secondaryColor: "#FFFFFF",
  colorBalance: 72,
  aliases: ["Fortuna Düsseldorf"],
  shirtImageUrl: "/shirts/germany/2-bundesliga/fortuna-dusseldorf.png",
},
{
  id: "greuther-furth",
  name: "Greuther Fürth",
  country: "Germany",
  league: "2. Bundesliga",
  logoUrl: "/logos/germany/2-bundesliga/greuther-furth.png",
  primaryColor: "#00853F",
  secondaryColor: "#FFFFFF",
  colorBalance: 70,
  aliases: ["SpVgg Greuther Fürth"],
  shirtImageUrl: "/shirts/germany/2-bundesliga/greuther-furth.png",
},
{
  id: "hannover",
  name: "Hannover",
  country: "Germany",
  league: "2. Bundesliga",
  logoUrl: "/logos/germany/2-bundesliga/hannover.png",
  primaryColor: "#00853F",
  secondaryColor: "#000000",
  colorBalance: 64,
  aliases: ["Hannover 96"],
  shirtImageUrl: "/shirts/germany/2-bundesliga/hannover.png",
},
{
  id: "hertha-bsc",
  name: "Hertha",
  country: "Germany",
  league: "2. Bundesliga",
  logoUrl: "/logos/germany/2-bundesliga/hertha-bsc.png",
  primaryColor: "#0057B8",
  secondaryColor: "#FFFFFF",
  colorBalance: 70,
  aliases: ["Hertha BSC"],
  shirtImageUrl: "/shirts/germany/2-bundesliga/hertha-bsc.png",
},
{
  id: "holstein-kiel",
  name: "Holstein",
  country: "Germany",
  league: "2. Bundesliga",
  logoUrl: "/logos/germany/2-bundesliga/holstein-kiel.png",
  primaryColor: "#0057B8",
  secondaryColor: "#FFFFFF",
  colorBalance: 72,
  aliases: ["Holstein Kiel"],
  shirtImageUrl: "/shirts/germany/2-bundesliga/holstein-kiel.png",
},
{
  id: "kaiserslautern",
  name: "Kaiserslautern",
  country: "Germany",
  league: "2. Bundesliga",
  logoUrl: "/logos/germany/2-bundesliga/kaiserslautern.png",
  primaryColor: "#D71920",
  secondaryColor: "#FFFFFF",
  colorBalance: 72,
  aliases: ["1. FC Kaiserslautern"],
  shirtImageUrl: "/shirts/germany/2-bundesliga/kaiserslautern.png",
},
{
  id: "karlsruhe",
  name: "Karlsruhe",
  country: "Germany",
  league: "2. Bundesliga",
  logoUrl: "/logos/germany/2-bundesliga/karlsruhe.png",
  primaryColor: "#003A8F",
  secondaryColor: "#FFFFFF",
  colorBalance: 72,
  aliases: ["Karlsruher SC", "KSC"],
  shirtImageUrl: "/shirts/germany/2-bundesliga/karlsruhe.png",
},
{
  id: "magdeburg",
  name: "Magdeburg",
  country: "Germany",
  league: "2. Bundesliga",
  logoUrl: "/logos/germany/2-bundesliga/magdeburg.png",
  primaryColor: "#0057B8",
  secondaryColor: "#FFFFFF",
  colorBalance: 70,
  aliases: ["1. FC Magdeburg"],
  shirtImageUrl: "/shirts/germany/2-bundesliga/magdeburg.png",
},
{
  id: "nurnberg",
  name: "Nürnberg",
  country: "Germany",
  league: "2. Bundesliga",
  logoUrl: "/logos/germany/2-bundesliga/nurnberg.png",
  primaryColor: "#8A1538",
  secondaryColor: "#FFFFFF",
  colorBalance: 72,
  aliases: ["1. FC Nürnberg"],
  shirtImageUrl: "/shirts/germany/2-bundesliga/nurnberg.png",
},
{
  id: "paderborn",
  name: "Paderborn",
  country: "Germany",
  league: "2. Bundesliga",
  logoUrl: "/logos/germany/2-bundesliga/paderborn.png",
  primaryColor: "#0057B8",
  secondaryColor: "#000000",
  colorBalance: 68,
  aliases: ["SC Paderborn 07"],
  shirtImageUrl: "/shirts/germany/2-bundesliga/paderborn.png",
},
{
  id: "preussen-munster",
  name: "Preußen Münster",
  country: "Germany",
  league: "2. Bundesliga",
  logoUrl: "/logos/germany/2-bundesliga/preussen-munster.png",
  primaryColor: "#000000",
  secondaryColor: "#FFFFFF",
  colorBalance: 70,
  aliases: ["SC Preußen Münster"],
  shirtImageUrl: "/shirts/germany/2-bundesliga/preussen-munster.png",
},
{
  id: "schalke",
  name: "Schalke",
  country: "Germany",
  league: "2. Bundesliga",
  logoUrl: "/logos/germany/2-bundesliga/schalke-04.png",
  primaryColor: "#0057B8",
  secondaryColor: "#FFFFFF",
  colorBalance: 74,
  aliases: ["FC Schalke 04"],
  shirtImageUrl: "/shirts/germany/2-bundesliga/schalke.png",
},

    /* =========================
     BELGIUM — JUPILER PRO LEAGUE
     ========================= */

  {
    id: "anderlecht",
    name: "Anderlecht",
    country: "Belgium",
    league: "Jupiler Pro League",
    logoUrl: "/logos/belgium/jupiler-pro-league/anderlecht.png",
    primaryColor: "#512D6D",
    secondaryColor: "#FFFFFF",
    colorBalance: 72,
    aliases: ["RSC Anderlecht"],
    shirtImageUrl: "/shirts/belgium/jupiler-pro-league/anderlecht.png",
  },
  {
    id: "antwerp",
    name: "Antwerp",
    country: "Belgium",
    league: "Jupiler Pro League",
    logoUrl: "/logos/belgium/jupiler-pro-league/royal-antwerp.png",
    primaryColor: "#D71920",
    secondaryColor: "#FFFFFF",
    colorBalance: 72,
    aliases: ["Royal Antwerp", "Royal Antwerp FC"],
    shirtImageUrl: "/shirts/belgium/jupiler-pro-league/antwerp.png",
  },
  {
    id: "club-brugge",
    name: "Club Brugge",
    country: "Belgium",
    league: "Jupiler Pro League",
    logoUrl: "/logos/belgium/jupiler-pro-league/club-brugge.png",
    primaryColor: "#000000",
    secondaryColor: "#1E5AA8",
    colorBalance: 62,
    aliases: ["Club Brugge KV"],
    shirtImageUrl: "/shirts/belgium/jupiler-pro-league/club-brugge.png",
  },
  {
    id: "cercle-brugge",
    name: "Cercle Brugge",
    country: "Belgium",
    league: "Jupiler Pro League",
    logoUrl: "/logos/belgium/jupiler-pro-league/cercle-brugge.png",
    primaryColor: "#00853F",
    secondaryColor: "#000000",
    colorBalance: 68,
    aliases: ["Cercle Brugge KSV"],
    shirtImageUrl: "/shirts/belgium/jupiler-pro-league/cercle-brugge.png",
  },
  {
    id: "charleroi",
    name: "Charleroi",
    country: "Belgium",
    league: "Jupiler Pro League",
    logoUrl: "/logos/belgium/jupiler-pro-league/charleroi.png",
    primaryColor: "#000000",
    secondaryColor: "#FFFFFF",
    colorBalance: 74,
    aliases: ["Sporting Charleroi", "RC Sporting Charleroi"],
    shirtImageUrl: "/shirts/belgium/jupiler-pro-league/charleroi.png",
  },
  {
    id: "dender",
    name: "Dender",
    country: "Belgium",
    league: "Jupiler Pro League",
    logoUrl: "/logos/belgium/jupiler-pro-league/dender.png",
    primaryColor: "#274185",
    secondaryColor: "#FFFFFF",
    colorBalance: 70,
    aliases: ["FCV Dender"],
    shirtImageUrl: "/shirts/belgium/jupiler-pro-league/kortrijk.png",
  },
  {
    id: "genk",
    name: "Genk",
    country: "Belgium",
    league: "Jupiler Pro League",
    logoUrl: "/logos/belgium/jupiler-pro-league/racing-genk.png",
    primaryColor: "#0057B8",
    secondaryColor: "#FFFFFF",
    colorBalance: 74,
    aliases: ["KRC Genk"],
    shirtImageUrl: "/shirts/belgium/jupiler-pro-league/genk.png",
  },
  {
    id: "gent",
    name: "Gent",
    country: "Belgium",
    league: "Jupiler Pro League",
    logoUrl: "/logos/belgium/jupiler-pro-league/kaa-gent.png",
    primaryColor: "#0057B8",
    secondaryColor: "#FFFFFF",
    colorBalance: 72,
    aliases: ["KAA Gent"],
    shirtImageUrl: "/shirts/belgium/jupiler-pro-league/gent.png",
  },
  {
    id: "leuven",
    name: "OH Leuven",
    country: "Belgium",
    league: "Jupiler Pro League",
    logoUrl: "/logos/belgium/jupiler-pro-league/ohl.png",
    primaryColor: "#000000",
    secondaryColor: "#D71920",
    colorBalance: 62,
    aliases: ["Oud-Heverlee Leuven", "OHL"],
    shirtImageUrl: "/shirts/belgium/jupiler-pro-league/leuven.png",
  },
  {
    id: "mechelen",
    name: "KV Mechelen",
    country: "Belgium",
    league: "Jupiler Pro League",
    logoUrl: "/logos/belgium/jupiler-pro-league/kv-mechelen.png",
    primaryColor: "#FFD200",
    secondaryColor: "#D71920",
    colorBalance: 58,
    aliases: ["Mechelen"],
    shirtImageUrl: "/shirts/belgium/jupiler-pro-league/mechelen.png",
  },
  {
    id: "raal",
    name: "Raal La Louvière",
    country: "Belgium",
    league: "Jupiler Pro League",
    logoUrl: "/logos/belgium/jupiler-pro-league/raal-la-louviere.png",
    primaryColor: "#2F7946",
    secondaryColor: "#ffffff",
    colorBalance: 72,
    aliases: ["Raal"],
    shirtImageUrl: "/shirts/belgium/jupiler-pro-league/raal.png",
  },
  {
    id: "standard-liege",
    name: "Standard Liège",
    country: "Belgium",
    league: "Jupiler Pro League",
    logoUrl: "/logos/belgium/jupiler-pro-league/standard.png",
    primaryColor: "#D71920",
    secondaryColor: "#FFFFFF",
    colorBalance: 72,
    aliases: ["Standard", "Standard de Liège"],
    shirtImageUrl: "/shirts/belgium/jupiler-pro-league/standard-liege.png",
  },
  {
    id: "st-truiden",
    name: "STVV",
    country: "Belgium",
    league: "Jupiler Pro League",
    logoUrl: "/logos/belgium/jupiler-pro-league/stvv.png",
    primaryColor: "#FFD200",
    secondaryColor: "#0057B8",
    colorBalance: 62,
    aliases: ["Sint-Truiden", "Sint-Truidense VV"],
    shirtImageUrl: "/shirts/belgium/jupiler-pro-league/st-truiden.png",
  },
  {
    id: "union-sg",
    name: "Union Saint-Gilloise",
    country: "Belgium",
    league: "Jupiler Pro League",
    logoUrl: "/logos/belgium/jupiler-pro-league/union-saint-gilloise.png",
    primaryColor: "#FFD200",
    secondaryColor: "#1E3A8A",
    colorBalance: 60,
    aliases: ["Union SG", "Royale Union Saint-Gilloise"],
    shirtImageUrl: "/shirts/belgium/jupiler-pro-league/union-sg.png",
  },
  {
    id: "westerlo",
    name: "Westerlo",
    country: "Belgium",
    league: "Jupiler Pro League",
    logoUrl: "/logos/belgium/jupiler-pro-league/westerlo.png",
    primaryColor: "#FFD200",
    secondaryColor: "#0057B8",
    colorBalance: 60,
    aliases: ["KVC Westerlo"],
    shirtImageUrl: "/shirts/belgium/jupiler-pro-league/westerlo.png",
  },
  {
    id: "zulte-waregem",
    name: "Zulte Waregem",
    country: "Belgium",
    league: "Jupiler Pro League",
    logoUrl: "/logos/belgium/jupiler-pro-league/zulte-waregem.png",
    primaryColor: "#E21350",
    secondaryColor: "#FFD204",
    colorBalance: 80,
    aliases: ["Zulte", "Essevee"],
    shirtImageUrl: "/shirts/belgium/jupiler-pro-league/westerlo.png",
  },

  /* =========================
   SWEDEN — ALLSVENSKAN
   ========================= */

{
  id: "aik",
  name: "AIK",
  country: "Sweden",
  league: "Allsvenskan",
  logoUrl: "/logos/sweden/Allsvenskan/aik.png",
  primaryColor: "#000000",
  secondaryColor: "#F2C94C",
  colorBalance: 70,
  aliases: ["AIK Fotboll"],
  shirtImageUrl: "/shirts/sweden/Allsvenskan/aik.png",
},
{
  id: "bp",
  name: "BP",
  country: "Sweden",
  league: "Allsvenskan",
  logoUrl: "/logos/sweden/Allsvenskan/bp.png",
  primaryColor: "#D71920",
  secondaryColor: "#000000",
  colorBalance: 68,
  aliases: ["Brommapojkarna", "IF Brommapojkarna"],
  shirtImageUrl: "/shirts/sweden/Allsvenskan/bp.png",
},
{
  id: "degerfors",
  name: "Degerfors",
  country: "Sweden",
  league: "Allsvenskan",
  logoUrl: "/logos/sweden/Allsvenskan/degerfors.png",
  primaryColor: "#D71920",
  secondaryColor: "#FFFFFF",
  colorBalance: 72,
  aliases: ["Degerfors IF"],
  shirtImageUrl: "/shirts/sweden/Allsvenskan/degerfors.png",
},
{
  id: "djurgardens",
  name: "Djurgårdens",
  country: "Sweden",
  league: "Allsvenskan",
  logoUrl: "/logos/sweden/Allsvenskan/djurgardens.png",
  primaryColor: "#1E5AA8",
  secondaryColor: "#87CEEB",
  colorBalance: 66,
  aliases: ["Djurgårdens IF", "Djurgardens IF"],
  shirtImageUrl: "/shirts/sweden/Allsvenskan/djurgarden.png",
},
{
  id: "elfsborg",
  name: "Elfsborg",
  country: "Sweden",
  league: "Allsvenskan",
  logoUrl: "/logos/sweden/Allsvenskan/elfsborg.png",
  primaryColor: "#F2C94C",
  secondaryColor: "#000000",
  colorBalance: 72,
  aliases: ["IF Elfsborg"],
  shirtImageUrl: "/shirts/sweden/Allsvenskan/elfsborg.png",
},
{
  id: "gais",
  name: "GAIS",
  country: "Sweden",
  league: "Allsvenskan",
  logoUrl: "/logos/sweden/Allsvenskan/gais.png",
  primaryColor: "#00853F",
  secondaryColor: "#000000",
  colorBalance: 66,
  aliases: ["GAIS Göteborg"],
  shirtImageUrl: "/shirts/sweden/Allsvenskan/gais.png",
},
{
  id: "hacken",
  name: "Häcken",
  country: "Sweden",
  league: "Allsvenskan",
  logoUrl: "/logos/sweden/Allsvenskan/hacken.png",
  primaryColor: "#F2C94C",
  secondaryColor: "#000000",
  colorBalance: 74,
  aliases: ["BK Häcken", "BK Hacken"],
  shirtImageUrl: "/shirts/sweden/Allsvenskan/hacken.png",
},
{
  id: "halmstad",
  name: "Halmstad",
  country: "Sweden",
  league: "Allsvenskan",
  logoUrl: "/logos/sweden/Allsvenskan/halmstad.png",
  primaryColor: "#0057B8",
  secondaryColor: "#000000",
  colorBalance: 64,
  aliases: ["Halmstads BK"],
  shirtImageUrl: "/shirts/sweden/Allsvenskan/halmstad.png",
},
{
  id: "hammarby",
  name: "Hammarby",
  country: "Sweden",
  league: "Allsvenskan",
  logoUrl: "/logos/sweden/Allsvenskan/hammarby.png",
  primaryColor: "#00853F",
  secondaryColor: "#FFFFFF",
  colorBalance: 72,
  aliases: ["Hammarby IF"],
  shirtImageUrl: "/shirts/sweden/Allsvenskan/hammarby.png",
},
{
  id: "ifk-goteborg",
  name: "IFK Göteborg",
  country: "Sweden",
  league: "Allsvenskan",
  logoUrl: "/logos/sweden/Allsvenskan/ifk-goteborg.png",
  primaryColor: "#0057B8",
  secondaryColor: "#FFFFFF",
  colorBalance: 74,
  aliases: ["IFK Goteborg", "Göteborg"],
  shirtImageUrl: "/shirts/sweden/Allsvenskan/ifk-goteborg.png",
},
{
  id: "kalmar",
  name: "Kalmar",
  country: "Sweden",
  league: "Allsvenskan",
  logoUrl: "/logos/sweden/Allsvenskan/kalmar.png",
  primaryColor: "#D71920",
  secondaryColor: "#FFFFFF",
  colorBalance: 70,
  aliases: ["Kalmar FF"],
  shirtImageUrl: "/shirts/sweden/Allsvenskan/kalmar.png",
},
{
  id: "malmo",
  name: "Malmö",
  country: "Sweden",
  league: "Allsvenskan",
  logoUrl: "/logos/sweden/Allsvenskan/malmo.png",
  primaryColor: "#87CEEB",
  secondaryColor: "#FFFFFF",
  colorBalance: 72,
  aliases: ["Malmö FF", "Malmo FF"],
  shirtImageUrl: "/shirts/sweden/Allsvenskan/malmo.png",
},
{
  id: "mjallby",
  name: "Mjällby",
  country: "Sweden",
  league: "Allsvenskan",
  logoUrl: "/logos/sweden/Allsvenskan/mjallby.png",
  primaryColor: "#FFD200",
  secondaryColor: "#000000",
  colorBalance: 70,
  aliases: ["Mjällby AIF", "Mjallby AIF"],
  shirtImageUrl: "/shirts/sweden/Allsvenskan/mjallby.png",
},
{
  id: "orgryte",
  name: "Örgryte",
  country: "Sweden",
  league: "Allsvenskan",
  logoUrl: "/logos/sweden/Allsvenskan/orgryte.png",
  primaryColor: "#D71920",
  secondaryColor: "#1E5AA8",
  colorBalance: 66,
  aliases: ["Örgryte IS", "Orgryte IS"],
  shirtImageUrl: "/shirts/sweden/Allsvenskan/orgryte.png",
},
{
  id: "sirius",
  name: "Sirius",
  country: "Sweden",
  league: "Allsvenskan",
  logoUrl: "/logos/sweden/Allsvenskan/sirius.png",
  primaryColor: "#1E5AA8",
  secondaryColor: "#000000",
  colorBalance: 68,
  aliases: ["IK Sirius"],
  shirtImageUrl: "/shirts/sweden/Allsvenskan/sirius.png",
},
{
  id: "vasteras",
  name: "Västerås",
  country: "Sweden",
  league: "Allsvenskan",
  logoUrl: "/logos/sweden/Allsvenskan/vasteras.png",
  primaryColor: "#00853F",
  secondaryColor: "#FFFFFF",
  colorBalance: 70,
  aliases: ["Västerås SK", "Vasteras SK"],
  shirtImageUrl: "/shirts/sweden/Allsvenskan/vasteras.png",
},

  /* ======================
     PLACEHOLDERS — OTHER
     ====================== */

  {
    id: "custom-club",
    name: "Custom Club",
    country: "Other",
    league: "Other",
    logoUrl: "",
    primaryColor: "#111111",
    secondaryColor: "#FFFFFF",
    colorBalance: 70,
    aliases: ["Other club", "Andere club"],
  },
];

/* ---------------- HELPERS ---------------- */

function norm(v: string) {
  return v.trim().toLowerCase();
}

export function getClubPresetByName(name: string) {
  const input = norm(name);

  return clubPresets.find((club) => {
    if (norm(club.name) === input) return true;
    if (club.aliases?.some((alias) => norm(alias) === input)) return true;
    return false;
  });
}

export function getClubPresetsByCountry(country: string) {
  return clubPresets.filter((club) => norm(club.country) === norm(country));
}

export function getClubPresetsByCountryAndLeague(country: string, league: string) {
  return clubPresets.filter(
    (club) =>
      norm(club.country) === norm(country) &&
      norm(club.league) === norm(league)
  );
}

export const clubPresetGroups = {
  netherlands: {
    label: "Netherlands",
    leagues: {
      eredivisie: clubPresets.filter(
        (club) => club.country === "Netherlands" && club.league === "Eredivisie"
      ),
      kkd: clubPresets.filter(
        (club) => club.country === "Netherlands" && club.league === "KKD"
      ),
    },
  },
};